### PR TITLE
[SYSTEMML-1694] Add snapshot version number to docs header

### PR DESCRIPTION
**Pull request by opengjenkins**

### CODE REVIEW

**Comment by akchinSTC** [comment]
Can an Admin verify this patch?

**Comment by deroneriksson** [comment]
Test this Jenkins

**Comment by deroneriksson** [comment]
add to whitelist.

**Comment by deroneriksson** [comment]
LGTM. Thank you @opengjenkins!

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1588/

**Pull request closed without merging**
