### PR TITLE
[SYSTEMML-1802] Fix build failure for distribution profile on Windows

### PR DESCRIPTION
**Pull request by niketanpansare**
- To test please run `mvn package -P distribution` on Windows machine

@gweidner can you please review this PR ?

### CODE REVIEW

**Comment by gweidner** [comment]
Here are artifacts from master with `mvn clean package -P distribution`:
artifacts_master

**Comment by gweidner** [comment]
But this is the build error observed on my system when applying the change:
pr_build_error

**Comment by niketanpansare** [comment]
Interesting .. I am getting an error without this fix via eclipse. 

I have updated the PR.  Can you please try again ?

**Comment by gweidner** [comment]
That works!  Attaching screen captures showing pr build success and artifacts.
pr_build_success

artifacts_pr

**Comment by niketanpansare** [comment]
Thanks Glenn. I will merge :+1:

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1806/

**Pull request closed without merging**
