### PR TITLE
[MINOR] Move refactor dev `docs` to `dev` folder

### PR DESCRIPTION
**Pull request by j143**
Prepare for the `gh-pages` branch.

cc @mboehm7 @Baunsgaard

### CODE REVIEW

**Comment by j143** [comment]
@kev-inn - Is this change okay for you.

**Comment by kev-inn** [comment]
I believe the files `docs/README.md`, `docs/builtins-reference.md` and `docs/dml-language-reference.md` would not make much sense in the dev directory since they are also written for actual users of the system.

Since this is in preperation for the `gh-pages` branch merge I might be missing some aspect, which would explain the idea behind the move of those files.

**Comment by j143** [comment]
Yes, Thanks @kev-inn . Since the content from the `gh-pages` branch into `docs` folder. For now, can we move this into dev folder? 

Once, the gh-pages branch is merged into this one, can we think about where we can place `docs/README.md`, `docs/builtins-reference.md` and `docs/dml-language-reference.md`.

 Does this look good to you.

**Comment by kev-inn** [comment]
Sounds good to me, sorry for my initial confusion. :+1:

**Comment by j143** [comment]
Thank Kevin & Sebastian. Got +2
I will merge.

**Pull request closed without merging**
