### PR TITLE
[MINOR] Fix Badges with links

### PR DESCRIPTION
**Pull request by Baunsgaard**
- Fix badges to only reflect status on push to master branch
- Make badges link to the tests conducted.

### CODE REVIEW

**Comment by j143** [comment]
This looks good to me. Thank you.

**Comment by j143** [comment]
If the commit is ready to be merged adding a line `closes #903. ` helps us merge on the github itself.

**Comment by mboehm7** [comment]
since the OSS release in 2015, we try to avoid direct merges (to prevent merge commits and other anomalies) - please, follow https://gist.github.com/deroneriksson/e0d6d0634f3388f0df5e

**Comment by mboehm7** [comment]
thanks @Baunsgaard and @j143

**Pull request closed without merging**
