### PR TITLE
[SYSTEMML-1799] Remove ppred from test scripts

### PR DESCRIPTION
**Pull request by deroneriksson**
Replace ppred functions with relational operators in test scripts since
ppred() is deprecated.

### CODE REVIEW

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1797/

**Comment by deroneriksson** [comment]
Thanks for reviewing @dusenberrymw. I renamed the test classes in the first commit and then updated the majority of the content in the second commit to preserve the history for these files.

**Comment by deroneriksson** [comment]
Thanks @dusenberrymw. I'll merge after successful completion of tests.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1804/

**Pull request closed without merging**
