### PR TITLE
[WIP][SYSTEMML-1645] Verify whether all scripts work with MLContext & automate

### PR DESCRIPTION
**Pull request by j143**
Test all the top level algorithms with ML Context.

1. Linear Regression Scripts.
    - [x] works fine
    - [ ] automate
2. StepLinear Regression Script
    - [x] works fine #525 
    - [ ] automate
3. SVM
    - [ ] works fine #529 
    - [ ] automate
4. Survival analysis algorithms   
    - [ ] works fine
    - [ ] automate
5. ALS
    - [x] works fine
    - [ ] automate
6. Logistic Regression
    - [ ] works fine
    - [ ] automate

### CODE REVIEW

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1794/

**Comment by j143** [comment]
cc @deroneriksson . To my understanding I used a lite random matrices as inputs and provided some general parameter values, and wrote output to the output matrix for different modes(probability dist.). Is it the way to do this?. I'll correct the syntax errors in the next commit.

**Comment by deroneriksson** [comment]
Thank you @j143. I think this is a good start so far (definitely fix syntax errors in next commit).

I'm not a data scientist so I'd say I'm not really a good judge of the exact nature of how the algorithm should be tested. I would have a look at `org.apache.sysml.test.integration.functions.codegen.AlgorithmGLM` and possibly replicate some of the same types of tests but run through MLContext, and it looks like you are indeed following that approach. From a software engineering perspective, I would examine the GLM.dml script and look to execute as many of the code paths resulting from the various conditions as possible. Perhaps @mboehm7 could provide further assistance.

Please also add the MLContextGLMTest class to src/test_suites/java/org/apache/sysml/test/integration/mlcontext/algorithms/ZPackageSuite.java.

**Comment by deroneriksson** [comment]
Also note that the input parameters (such as "$dfam") will probably need "$" prepended to their names when being set through the MLContext API.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1817/

**Comment by j143** [comment]
@deroneriksson can you help me with correcting the syntax. Honestly, this is the first java code I've ever written in my life. 😢  I tried to copy your code style.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1818/

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1819/

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1820/

**Comment by deroneriksson** [comment]
Hi @j143. Thank you for working on this.

You probably will need to be developing in an IDE such as Eclipse or IntelliJ in order to work on test classes such as this. The IDE will automatically alert you to syntax issues (currently Eclipse says that there are 6 syntax errors) and can also make it very easy to run the test classes in order to verify that they work. There is a lot of general information on the web that can be found regarding Eclipse/IntelliJ/Maven/Java, and most of this information applies to SystemML since it is essentially a regular Java project with a standard build system.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1928/

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1929/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1929/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1929/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.data/FullReblockTest/testCSVSingeMSparseMR/'><strong>org.apache.sysml.test.integration.functions.data.FullReblockTest.testCSVSingeMSparseMR</strong></a></li></ul>

**Comment by j143** [comment]
Test this Jenkins

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1932/

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1939/<h2>Failed Tests: <span class='status-failure'>8</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1939/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>8</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1939/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMGammaSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMGammaSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1939/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPoissonSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPoissonSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1939/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMGammaDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMGammaDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1939/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMBinomialSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMBinomialSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1939/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPoissonDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPoissonDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1939/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMBinomialDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMBinomialDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1939/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextLinregCGTest/testLinregCGDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextLinregCGTest.testLinregCGDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1939/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextLinregCGTest/testLinregCGSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextLinregCGTest.testLinregCGSparse</strong></a></li></ul>

**Comment by j143** [comment]
@mboehm7 can you please take a look at this?. Instead, of heavier matrices, I am only using lite matrices `getRandomMatrix(10, 3, 0, 1, sparse?sparsity2:sparsity1, -1)` to test with `mlcontext`. Thanks.

**Comment by j143** [comment]
Seems `GLM.dml` have some issues with mlc.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1963/

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1964/<h2>Failed Tests: <span class='status-failure'>12</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1964/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>12</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1964/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMGammaSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMGammaSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1964/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPoissonSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPoissonSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1964/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMGammaDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMGammaDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1964/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMBinomialSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMBinomialSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1964/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPoissonDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPoissonDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1964/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMBinomialDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMBinomialDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1964/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/org_apache_sysml_test_integration_mlcontext_algorithms_MLContextGLMTest/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1964/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextLinregTest/testLinregCGDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextLinregTest.testLinregCGDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1964/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextLinregTest/testLinregDSSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextLinregTest.testLinregDSSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1964/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextLinregTest/testLinregDSDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextLinregTest.testLinregDSDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1964/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextLinregTest/testLinregCGSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextLinregTest.testLinregCGSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1964/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextLinregTest/org_apache_sysml_test_integration_mlcontext_algorithms_MLContextLinregTest/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextLinregTest.org.apache.sysml.test.integration.mlcontext.algorithms.MLContextLinregTest</strong></a></li></ul>

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1971/<h2>Failed Tests: <span class='status-failure'>13</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1971/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>13</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1971/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMGammaSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMGammaSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1971/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPoissonSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPoissonSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1971/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMGammaDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMGammaDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1971/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMBinomialSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMBinomialSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1971/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPoissonDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPoissonDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1971/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMBinomialDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMBinomialDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1971/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextLinregTest/testLinregCGDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextLinregTest.testLinregCGDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1971/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextLinregTest/testLinregDSSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextLinregTest.testLinregDSSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1971/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextLinregTest/testLinregDSDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextLinregTest.testLinregDSDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1971/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextLinregTest/testLinregCGSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextLinregTest.testLinregCGSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1971/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextSVMTest/testL2SVMSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextSVMTest.testL2SVMSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1971/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextSVMTest/testMSVMDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextSVMTest.testMSVMDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1971/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextSVMTest/testMSVMSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextSVMTest.testMSVMSparse</strong></a></li></ul>

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1972/<h2>Failed Tests: <span class='status-failure'>13</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1972/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>13</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1972/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMGammaSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMGammaSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1972/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPoissonSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPoissonSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1972/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMGammaDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMGammaDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1972/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMBinomialSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMBinomialSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1972/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPoissonDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPoissonDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1972/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMBinomialDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMBinomialDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1972/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextLinregTest/testLinregCGDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextLinregTest.testLinregCGDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1972/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextLinregTest/testLinregDSSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextLinregTest.testLinregDSSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1972/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextLinregTest/testLinregDSDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextLinregTest.testLinregDSDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1972/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextLinregTest/testLinregCGSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextLinregTest.testLinregCGSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1972/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextSVMTest/testL2SVMSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextSVMTest.testL2SVMSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1972/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextSVMTest/testMSVMDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextSVMTest.testMSVMDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1972/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextSVMTest/testMSVMSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextSVMTest.testMSVMSparse</strong></a></li></ul>

**Comment by j143** [comment]
with @deroneriksson 's suggestion, I am closing this PR and will be addressing the each script individually. Thanks.

**Pull request closed without merging**
