### PR TITLE
[SYSTEMML-445] [MINOR] Added slice_dense_dense kernel for right indexing, bufferpool bugfix and refactor asserts to exceptions

### PR DESCRIPTION
**Pull request by niketanpansare**
@nakul02 can you please review this PR ?

### CODE REVIEW

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2088/

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2089/

**Comment by nakul02** [comment]
@niketanpansare - if its not too much trouble, could you please split just disabling rightIndexing into a different PR than refactoring asserts and other minor optimizations? That way, we could test the impact of the optimizations separately from just disabling rightIndexing.

**Comment by nakul02** [comment]
LGTM 👍 
Please merge. This fixes the performance problems I've been seeing with GPU right indexing.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2094/

**Pull request closed without merging**
