### PR TITLE
[DOC] Factorization Machines core module

### PR DESCRIPTION
**Pull request by j143**
_what does this contain?_
1. model equation
2. little theoretical support
3. calculations as to how order of computation changed.
4. gradients

_what's later_
1. once @dusenberrymw reviews & merges classification & regression, documentation will be added for them also.

Thanks a lot.

### CODE REVIEW

**Comment by j143** [comment]
@dusenberrymw - please provide any comments as to what else needs to be added.
@krishnakalyan3 - can I get a preliminary review, just copy the changeset & paste it at [upmath.me](https://upmath.me/)  to get real time rendering.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2275/

**Comment by krishnakalyan3** [comment]
@j143 thanks for working on this. Initial version looks good.

**Comment by j143** [comment]
@dusenberrymw , can this doc also be added as a preliminary version, for now.

We can write a full doc when scale the **fm** scripts, after few months. Thanks.

**Comment by dusenberrymw** [comment]
@j143 Can you push a copy of the built docs to a `gh-pages` branch in your systemml fork so that it can be viewed in web form for review?  It only takes a minute: http://apache.github.io/systemml/contributing-to-systemml#documentation.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2348/

**Comment by prithvirajsen** [comment]
Hi @j143 
Looks like a decent intro to factorization machines. Thanks for adding.
Possible improvements could be a section on how to invoke the accompanying factorization machine script (so that some1 who is not interested in the theory could get started quickly). Please let me know in case that part of the documentation is somewhere else.

**Comment by prithvirajsen** [comment]
Well, if the goal is simply to add an fm layer, then I guess its fine (I wasn't suggesting adding a standalone dml implementation).

I looked for documentation on nn layers and seems like we have very sparse docs. For instance, I couldn't find any documentation explaining at an intuitive, abstract level what conv2d does. That's what I was suggesting. For the standalone dml algos we have a pdf file with such info.

So feel free to ignore my previous comment. Seems like the comments in the fm layer's implementation are supposed to serve as sufficient description.

**Comment by prithvirajsen** [comment]
sounds good

**Pull request merged**
