### PR TITLE
[SYSTEMML-493]Functionalize PCA

### PR DESCRIPTION
**Pull request by krishnakalyan3**
Changes include wrapping PCA computation to a function call.

### CODE REVIEW

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2041/

**Comment by j143** [comment]
Hi Krishna, it's nice. Do you want to give a simple try over a real dataset such as [
Glass Identification Data Set](https://archive.ics.uci.edu/ml/machine-learning-databases/glass/glass.data), to test.(?)

**Comment by krishnakalyan3** [comment]
@j143 could you please clarify. Do you mean add specific test case like [here](https://github.com/apache/systemml/pull/647)

**Comment by krishnakalyan3** [comment]
ping @deroneriksson could you please review this PR?.

**Comment by nakul02** [comment]
@krishnakalyan3 - this is good work.
Here are a couple of things I'd suggest. 

- Compare results from this version to scikit or some other package you **trust** to some reasonable degree of accuracy. Not being very knowledgable in the domain, I'll leave it to you to decide what that is. Make sure to test against real and artificial data.
- Compare results from this version to the previous version of `PCA.dml`. For results and performance. Single node and spark/hybrid_spark mode.
- Write automated tests for this script. That could mean something that looks like PR #647 or something else.

**Comment by krishnakalyan3** [comment]
@nakul02 thanks for the feedback.

**Comment by j143** [comment]
@krishnakalyan3 please also note that #647 is for checking only the I.O. behaviour w/ MLContext. Along with that
1. so here, you might want first test on a real world dataset, as @nakul02 pointed out. 
2. From the existing [RandData](https://github.com/apache/systemml/blob/5decbe64b362e29901f15231c672c7b7816ed55a/scripts/datagen/genRandData4PCA.dml) , keep the output in such a way as to get a null matrix so that we can verify that w/ a test class with some tolerance (`1e-6`).

**Comment by nakul02** [comment]
@krishnakalyan3 - any updates?

**Comment by deroneriksson** [comment]
Hi @krishnakalyan3 @nakul02 @j143,

In my opinion, this PR focuses on functionalizing PCA ([SYSTEMML-493](https://issues.apache.org/jira/browse/SYSTEMML-493)), and we should really stay focused on that task, which is functionalizing the existing algorithm. I believe it can be validated using existing code in the project (it appears that it can be validated with runAllDimensionReduction.sh, which generates PCA data and then runs PCA.dml on that data). So perhaps Krishna can simply validate that the new script runs with runAllDimensionReduction.sh? If the functionalized PCA script runs like the non-functionalized PCA script, then it can be merged.

Additional tasks such as automated testing could be performed as additional PRs. For example, an automated MLContext PCA test JIRA could be created under [SYSTEMML-1645](https://issues.apache.org/jira/browse/SYSTEMML-1645). The SystemML project as a whole could definitey use improved algorithm testing, but I think issues like that should be handled in separate PRs.

Perhaps a comment could be added to the staging/PCA.dml file indicating that this script is a functionalized version of the original PCA.dml script?

cc @dusenberrymw

**Comment by nakul02** [comment]
Thanks @deroneriksson - that is a very good suggestion. 

@krishnakalyan3 - I like @deroneriksson's idea to treat this PR just for the refactoring of the algorithm and then adding the test in a separate PR. I will wait for a someone knowledgeable in the domain to give you a LGTM. 
In the meantime, whenever you are done testing your script using the method deron suggested, please comment on this PR. We'll wait for that and a domain experts review before merging.

**Comment by krishnakalyan3** [comment]
@nakul02 @deroneriksson @j143 thank you for your feedback and reviews. I have tested with `genRandData4PCA.dml` verified the values of `eigen vectors` and `eigen values` match with the older script.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2107/<h2>Failed Tests: <span class='status-failure'>6</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2107/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>6</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2107/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.misc/RewriteElementwiseMultChainOptimizationAllTest/testMatrixMultChainOptNoRewritesCP/'><strong>org.apache.sysml.test.integration.functions.misc.RewriteElementwiseMultChainOptimizationAllTest.testMatrixMultChainOptNoRewritesCP</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2107/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.misc/RewriteElementwiseMultChainOptimizationAllTest/testMatrixMultChainOptRewritesCP/'><strong>org.apache.sysml.test.integration.functions.misc.RewriteElementwiseMultChainOptimizationAllTest.testMatrixMultChainOptRewritesCP</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2107/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.misc/RewriteElementwiseMultChainOptimizationTest/testMatrixMultChainOptNoRewritesCP/'><strong>org.apache.sysml.test.integration.functions.misc.RewriteElementwiseMultChainOptimizationTest.testMatrixMultChainOptNoRewritesCP</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2107/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.misc/RewriteElementwiseMultChainOptimizationTest/testMatrixMultChainOptRewritesCP/'><strong>org.apache.sysml.test.integration.functions.misc.RewriteElementwiseMultChainOptimizationTest.testMatrixMultChainOptRewritesCP</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2107/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.misc/RewriteMatrixMultChainOptTest/testMatrixMultChainOptNoRewritesCP/'><strong>org.apache.sysml.test.integration.functions.misc.RewriteMatrixMultChainOptTest.testMatrixMultChainOptNoRewritesCP</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2107/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.misc/RewriteMatrixMultChainOptTest/testMatrixMultChainOptRewritesCP/'><strong>org.apache.sysml.test.integration.functions.misc.RewriteMatrixMultChainOptTest.testMatrixMultChainOptRewritesCP</strong></a></li></ul>

**Comment by j143** [comment]
Test this Jenkins

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2108/

**Comment by j143** [comment]
This looks fine.

**Comment by deroneriksson** [comment]
LGTM. Thank you @krishnakalyan3

**Pull request closed without merging**
