### PR TITLE
[SYSTEMML-445] Compilation bugfix for Mac OS and PowerPC arch.

### PR DESCRIPTION
**Pull request by niketanpansare**
@nakul02 @bertholdreinwald can you please test this PR on Mac OS ?

### CODE REVIEW

**Comment by akchinSTC** [comment]
Can an Admin verify this patch?

**Comment by nakul02** [comment]
Nope.
```
➜  systemml git:(bugfix_jcuda_apple) ✗ mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------< org.apache.systemml:systemml >--------------------
[INFO] Building SystemML 1.2.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.070 s
[INFO] Finished at: 2018-05-31T14:11:41-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project systemml: Could not resolve dependencies for project org.apache.systemml:systemml:jar:1.2.0-SNAPSHOT: The following artifacts could not be resolved: org.jcuda:jcuda-natives:jar:apple-x86_64:0.9.0d, org.jcuda:jcublas-natives:jar:apple-x86_64:0.9.0d, org.jcuda:jcusparse-natives:jar:apple-x86_64:0.9.0d, org.jcuda:jcusolver-natives:jar:apple-x86_64:0.9.0d, org.jcuda:jcudnn-natives:jar:apple-x86_64:0.9.0d: Failure to find org.jcuda:jcuda-natives:jar:apple-x86_64:0.9.0d in https://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
➜  systemml git:(bugfix_jcuda_apple) ✗
```

**Comment by niketanpansare** [comment]
@nakul02 can you try again ?

**Comment by bertholdreinwald** [comment]
LGTM

**Pull request closed without merging**
