### PR TITLE
[SYSTEMML-1992] Implemenation of Mode finding for Gaussian Process

### PR DESCRIPTION
**Pull request by j143**
First implementation of mode finding for the gaussian processes. 

**How it fits?**
*At the high level (as DML scripts)*

1. mode is in implementation. (`mode.dml`)
2. this will be used next script gaussian process classification. (`gpc.dml`)
3. then comes the gaussian process regression script. (`gpr.dml`)
4. using that outputs that we get from the above scripts, leave one out(LOO) cross validation script(`CV.dml`)
---------

*At low level (as java calls)*
1. we call the above functions from a  java class & train the scripts.

### CODE REVIEW

**Comment by j143** [comment]
Implemented algorithm:

mode_algo

**Comment by j143** [comment]
Hi @niketanpansare , 
I have tested the script with some dummy initialization, how to test it more solid. Thanks.
This script works only after applying #710 . 
Thanks.

**Comment by j143** [comment]
Hi @niketanpansare , tried to simplify the script for easy review. May be its good for merging.

**Comment by niketanpansare** [comment]
Hi Janardhan, I was planning to review this PR coming week. Do you plan to create a new PR ?

**Comment by j143** [comment]
Sorry, I accidentally done a `force push` during the `rebase`, I will add a test along with the algorithm. Thanks.

**Comment by j143** [comment]
Obtained from DML script (`mode.dml`):
-------------------------------------------
loglik_yf
Theoretical
------------------------------------------
theoretical_lik_vs_latent

**Comment by j143** [comment]
Hi @niketanpansare, If there is anything that I missed out here, please give me a hint.

Due to my academic life, I am planning to complete writing all the algorithm(there seems to be 5) by `7 Jan, 2018`. After which we can test it on real dataset, for I have a research committment with our Professor this Semester, which I have postponed last semester because of this feature.

Thanks. 

ps: I will delete this comment after sometime.

**Comment by niketanpansare** [comment]
I don’t think you are missing anything. Please go ahead and complete the algorithms as per your commitment :)

**Comment by j143** [comment]
Hi sir, 
can we start with this script?.

cc @niketanpansare

**Comment by j143** [comment]
Hi sir, 
can we start with this script?.

cc @niketanpansare

**Comment by akchinSTC** [comment]
Build finished.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2233/

**Comment by akchinSTC** [comment]
Test this Jenkins

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2234/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2234/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2234/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.applications.pydml/LinearLogRegPyDMLTest/testLinearLogRegPyDml_6_/'><strong>org.apache.sysml.test.integration.applications.pydml.LinearLogRegPyDMLTest.testLinearLogRegPyDml[6]</strong></a></li></ul>

**Comment by j143** [comment]
Hi @niketanpansare , review shouldn't take more that 10 mins, promise!. 

simply,
1. the algorithm steps are [in textbook](https://github.com/apache/systemml/pull/711#issuecomment-353591028) as it is.
2. the derivatives in step 4, & step 6 were found in the text, but they are correct.

Thanks.

**Comment by niketanpansare** [comment]
LGTM. Thanks @j143 👍

**Comment by j143** [comment]
Hi @dusenberrymw , you also want to take a look at this place?.

Thanks.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/<h2>Failed Tests: <span class='status-failure'>58</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>58</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.jmlc/MulticlassSVMScoreTest/testJMLCMulticlassScoreSparse/'><strong>org.apache.sysml.test.integration.functions.jmlc.MulticlassSVMScoreTest.testJMLCMulticlassScoreSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.codegen/CompressedRowAggregateLargeTest/testCompressedRowAggregateMainDenseConstCP/'><strong>org.apache.sysml.test.integration.functions.codegen.CompressedRowAggregateLargeTest.testCompressedRowAggregateMainDenseConstCP</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.codegen/CompressedRowAggregateLargeTest/testCompressedRowAggregateMainEmptyRandCP/'><strong>org.apache.sysml.test.integration.functions.codegen.CompressedRowAggregateLargeTest.testCompressedRowAggregateMainEmptyRandCP</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.codegen/CompressedRowAggregateLargeTest/testCompressedRowAggregateMainEmptyConstCP/'><strong>org.apache.sysml.test.integration.functions.codegen.CompressedRowAggregateLargeTest.testCompressedRowAggregateMainEmptyConstCP</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.codegen/CompressedRowAggregateLargeTest/testCompressedRowAggregateMainEmptyRand2CP/'><strong>org.apache.sysml.test.integration.functions.codegen.CompressedRowAggregateLargeTest.testCompressedRowAggregateMainEmptyRand2CP</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.codegen/CompressedRowAggregateLargeTest/testCompressedRowAggregateMainEmptyRand3CP/'><strong>org.apache.sysml.test.integration.functions.codegen.CompressedRowAggregateLargeTest.testCompressedRowAggregateMainEmptyRand3CP</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.codegen/CompressedRowAggregateLargeTest/testCompressedRowAggregateMainSparseConstCP/'><strong>org.apache.sysml.test.integration.functions.codegen.CompressedRowAggregateLargeTest.testCompressedRowAggregateMainSparseConstCP</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeCompressionTest/testSparseConstDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeCompressionTest.testSparseConstDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeCompressionTest/testDenseConstantDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeCompressionTest.testDenseConstantDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeCompressionTest/testEmptyCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeCompressionTest.testEmptyCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeMatrixVectorMultTest/testSparseConstDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeMatrixVectorMultTest.testSparseConstDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeMatrixVectorMultTest/testDenseConstantDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeMatrixVectorMultTest.testDenseConstantDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeMatrixVectorMultTest/testEmptyCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeMatrixVectorMultTest.testEmptyCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParMatrixVectorMultTest/testSparseConstDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParMatrixVectorMultTest.testSparseConstDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParMatrixVectorMultTest/testDenseConstantDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParMatrixVectorMultTest.testDenseConstantDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParMatrixVectorMultTest/testEmptyCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParMatrixVectorMultTest.testEmptyCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testRowMaxsEmptyCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testRowMaxsEmptyCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testMinSparseConstDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testMinSparseConstDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testColSumsSqEmptyCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testColSumsSqEmptyCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testSumSparseConstDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testSumSparseConstDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testRowSumsEmptyCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testRowSumsEmptyCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testRowSumsDenseConstantDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testRowSumsDenseConstantDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testColMaxsEmptyCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testColMaxsEmptyCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testColSumsSqSparseConstDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testColSumsSqSparseConstDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testColSumsEmptyCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testColSumsEmptyCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testColSumsSqDenseConstantDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testColSumsSqDenseConstantDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testSumDenseConstantDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testSumDenseConstantDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testMinEmptyCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testMinEmptyCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testSumSqEmptyCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testSumSqEmptyCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testMaxEmptyCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testMaxEmptyCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testRowMaxsDenseConstantDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testRowMaxsDenseConstantDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testMaxDenseConstantDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testMaxDenseConstantDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testColMinsDenseConstantDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testColMinsDenseConstantDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testColMinsSparseConstDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testColMinsSparseConstDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testColSumsSparseConstDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testColSumsSparseConstDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testRowSumsSqSparseConstDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testRowSumsSqSparseConstDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testColSumsDenseConstantDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testColSumsDenseConstantDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testSumSqDenseConstantDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testSumSqDenseConstantDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testColMaxsSparseConstDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testColMaxsSparseConstDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testMaxSparseConstDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testMaxSparseConstDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testSumSqSparseConstDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testSumSqSparseConstDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testRowMinsEmptyCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testRowMinsEmptyCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testRowSumsSqDenseConstantDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testRowSumsSqDenseConstantDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testRowMinsSparseConstDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testRowMinsSparseConstDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testColMaxsDenseConstantDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testColMaxsDenseConstantDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testRowSumsSparseConstDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testRowSumsSparseConstDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testColMinsEmptyCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testColMinsEmptyCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testMinDenseConstantDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testMinDenseConstantDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testRowMinsDenseConstantDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testRowMinsDenseConstantDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testRowSumsSqEmptyCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testRowSumsSqEmptyCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testRowMaxsSparseConstDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testRowMaxsSparseConstDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeParUnaryAggregateTest/testSumEmptyCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeParUnaryAggregateTest.testSumEmptyCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeVectorMatrixMultTest/testSparseConstDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeVectorMatrixMultTest.testSparseConstDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeVectorMatrixMultTest/testDenseConstantDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeVectorMatrixMultTest.testDenseConstantDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/LargeVectorMatrixMultTest/testEmptyCompression/'><strong>org.apache.sysml.test.integration.functions.compress.LargeVectorMatrixMultTest.testEmptyCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/ParCompressionTest/testSparseConstDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.ParCompressionTest.testSparseConstDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/ParCompressionTest/testDenseConstantDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.ParCompressionTest.testDenseConstantDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2240/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/ParCompressionTest/testEmptyCompression/'><strong>org.apache.sysml.test.integration.functions.compress.ParCompressionTest.testEmptyCompression</strong></a></li></ul>

**Comment by j143** [comment]
Hi @niketanpansare , can this be merged. (I am only a contributor, now!). Thanks a lot.

**Comment by niketanpansare** [comment]
test this jenkins

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2242/

**Comment by niketanpansare** [comment]
[All tests](https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2242/) passed. I will merge. Thanks @j143 👍

**Pull request closed without merging**
