### PR TITLE
[SYSTEMML-1945] Performance Test, Update Deploy mode parameter

### PR DESCRIPTION
**Pull request by krishnakalyan3**
This PR, includes `--deploy-mode` argument to our performance test suit.  
[SYSTEMML-1945](https://issues.apache.org/jira/browse/SYSTEMML-1945)

### CODE REVIEW

**Comment by krishnakalyan3** [comment]
@nakul02 @gweidner could you please review this PR?.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2174/

**Comment by nakul02** [comment]
LGTM 👍 
I shall merge.

**Comment by krishnakalyan3** [comment]
Thank you for the review @nakul02 . :)

**Pull request closed without merging**
