### PR TITLE
[SYSTEMML-848] Create Release Creation Process doc

### PR DESCRIPTION
**Pull request by asurve**

### CODE REVIEW

**Comment by gweidner** [comment]
Thank you @asurve for updating the release document.  I viewed new content as web page under `bundle exec jekyll serve`.  Please make some minor formatting corrections to the new markdown file.  For example, `<br>` tokens can be removed.

**Comment by asurve** [comment]
thanks @gweidner Updated changes.

**Comment by gweidner** [comment]
LGTM - I will merge PR and push `gh-pages`.

**Comment by asurve** [comment]
Thanks @gweidner

**Pull request closed without merging**
