### PR TITLE
[MINOR] change CastAsScalar to as.scalar

### PR DESCRIPTION
**Pull request by j143**
1. change `castAsScalar` to `as.scalar` in a dml file.
2. change the opcode `CAST_AS_SCALAR` to an alternative at the engine level.

### CODE REVIEW

**Comment by j143** [comment]
Hi @deroneriksson , the following files seems to use `CAST_AS_SCALAR` opcode, shall we use some other opcode at these places.
`hops/TernaryOp.java` [L231](https://github.com/apache/systemml/blob/3ca05353593e7847dc6d6a7e862e323ffa96bfcc/src/main/java/org/apache/sysml/hops/TernaryOp.java#L231)
`QuaternaryOp.java`    [L438](https://github.com/apache/systemml/blob/8dbc93022a01aae309354c7b2b2f0eee9ec11aad/src/main/java/org/apache/sysml/hops/QuaternaryOp.java#L438)

**Comment by deroneriksson** [comment]
Hi @j143,
I once tried changing CAST_AS_SCALAR but changed it back after feedback from @mboehm7 (see https://github.com/apache/systemml/pull/130). Perhaps @mboehm7 can advise WRT this issue.

**Comment by j143** [comment]
So, we need to differentiate PyDML(`scalar`) & DML(`as.scalar`)  `BuiltinFunctionExpression`, may be with a boolean flag, for language level warning.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2152/

**Comment by mboehm7** [comment]
There is no need to change the internal operator types or opcodes. Updating the scripts to use as.scalar would be fine though. However, in this specific instance I would recommend to rather delete this test script and reference  `scripts/algorithms/LinearRegCG.dml` instead (see `codegen.AlgorithmLinregCG` for an example).

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2154/

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2155/

**Comment by j143** [comment]
Done!

**Comment by mboehm7** [comment]
great thanks @j143 - even though the tests are passing, could you please also (1) delete compress/LinregCG.R and reference codegen/Algorithm_LinregCG.R because it closely resembles our linregCG script in the algorithms folder.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2162/

**Comment by j143** [comment]
Hi @deroneriksson , this branch is a bit stale. Could you please have a look(?). Everything looked fine in my IDE.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2165/

**Comment by mboehm7** [comment]
LGTM - thanks @j143

**Pull request closed without merging**
