### PR TITLE
[SYSTEMML-1444][PART-2] UDFs w/ single output in expressions

### PR DESCRIPTION
**Pull request by j143**
It's been my third day with this PR, I am trying to change combinations & see correspondingly, what happens.. But, still the work in progress.

**Language changes / tests:** We need change of validation & tests.

Please give me a little more time, I will try to validate & de-duplicate the tests. Thanks.

### CODE REVIEW

**Comment by mboehm7** [comment]
If you're struggling with this, we might want to consider using a much simpler approach first. We could modify the parser to simply split the expressions into a form that the compiler and runtime can already handle. This would already solve the usability issues and we can subsequently have a closer look at the deep integration into compiler and runtime. If you need help, I could have a look tomorrow where exactly in the parser we would do that.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2285/

**Comment by akchinSTC** [comment]
RAT check failed for the following file: scripts/test.dml

**Comment by j143** [comment]
Hi @mboehm7 , sorry for being late. I will go through this again tonight and will note my progress.

**Comment by j143** [comment]
Hi @mboehm7 , I need some help in splitting this one. I was stuck at ctx.

Is this the mapping `ctx -> validate -> functionOp -> functionCallCPSingle()`.

**Comment by mboehm7** [comment]
Well, I think I should have been clearer since we use "parser" for both the antlr parser (the syntactic parser) and the language processing in the package parser (the semantic parser). For the simple "modify the parser" approach I mentioned earlier, I don't think we need changes to the antlr parser at all.

In detail, your dml is parsed into statement blocks and statements. Statements such as the AssignmentStatement (for X = ...) have an arbitrary expression on the right hand side. Function calls are represented as FunctionCallIdentifier, which is also an expression. However, in contrast to normal expressions, we currently require that the FunctionCallIdentifier is the right hand side of the assignment statement. So the splitting would essentially take an assignment statement such as X = Y + foo() and split it into TMP_hash = foo(); and X = TMP_hash. For the creation of unique temporary variable names, you can probably reuse the existing primitives we currently use for inlining.

**Comment by j143** [comment]
This one drained all my confidence for days. I will take this up, once after a while.

**Comment by j143** [comment]
Hi Matthias, can you address this one, if you have little time. Thanks.

**Comment by mboehm7** [comment]
sure - I'm happy to take it over. Thanks for your effort on it.

**Comment by mboehm7** [comment]
ok, I just pushed the change to master - if you rebase the PR, we can merge your additional tests in tomorrow as well.

**Comment by j143** [comment]
I've kept some two tests, and will try to modify after going through the algorithm use case later.

I am keeping a note in the dev list, to notify algorithm engineers.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2302/<h2>Failed Tests: <span class='status-failure'>2</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2302/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>2</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2302/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.misc/InvalidFunctionAssignmentTest/testInvalidFunctionAssignment/'><strong>org.apache.sysml.test.integration.functions.misc.InvalidFunctionAssignmentTest.testInvalidFunctionAssignment</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2302/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.misc/InvalidFunctionAssignmentTest/testInvalidFunctionAssignmentInlined/'><strong>org.apache.sysml.test.integration.functions.misc.InvalidFunctionAssignmentTest.testInvalidFunctionAssignmentInlined</strong></a></li></ul>

**Comment by mboehm7** [comment]
LGTM - thanks @j143. I just made a minor tweak to one of the tests to call the external function directly from the expression.

**Pull request closed without merging**
