### PR TITLE
[SYSTEMML-1907] Rename python package to systemml-*-python.tar.gz

### PR DESCRIPTION
**Pull request by gweidner**
Switched python artifact to tar.gz for PyPi upload compatibility with twine.
Also made corresponding updates to release validation utilities and documentation.

### CODE REVIEW

**Comment by gweidner** [comment]
Tested the following on linux:

`mvn clean package -DskipTests=true -P distribution`

`./release-verify.sh --compile`
`./release-verify.sh --verifyLic --distDir="../../target"`

`pip install ./target/systemml-1.0.0-SNAPSHOT-python.tar.gz`

Ran matrix example in PySpark. Verified distribution built on Windows from command line.

**Comment by gweidner** [comment]
If other artifacts need to be similarly switched from tgz to tar.gz, then a separate PR/JIRA can be opened.

**Comment by gweidner** [comment]
Note the website's install page "Dev Python (Latest code)" tab which references python artifact will be updated after PR merged.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2103/

**Comment by asurve** [comment]
Thanks @gweidner  
LGTM

**Comment by gweidner** [comment]
Thank you Arvind for reviewing!  I will merge.

**Pull request closed without merging**
