### PR TITLE
[MINOR] Fix sphinx build warnings for python documentation

### PR DESCRIPTION
**Pull request by gweidner**
Corrected two docstrings to prevent several warnings reported when using Sphinx to generate python documentation.

### CODE REVIEW

**Comment by gweidner** [comment]
Here are examples of the warnings messages:
systemml/src/main/python/systemml/defmatrix.py:docstring of systemml.defmatrix.matrix:65: WARNING: Enumerated list ends without a blank line; unexpected unindent.
src/main/python/systemml/mlcontext.py:docstring of systemml.mlcontext.getDatasetMean:2: (SEVERE/4) Unexpected section title.
systemml/src/main/python/systemml/__init__.py:docstring of systemml.matrix:65: WARNING: Enumerated list ends without a blank line; unexpected unindent.
src/main/python/systemml/__init__.py:docstring of systemml.getDatasetMean:2: (SEVERE/4) Unexpected section title.

**Comment by deroneriksson** [comment]
LGTM. Thank you @gweidner

**Comment by gweidner** [comment]
Thank you Deron for reviewing - I will merge after PR 639 closed.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2002/

**Pull request closed without merging**
