### PR TITLE
[SYSTEMML-1931] Support logical operators AND, NOT, OR over matrices, scalars combination

### PR DESCRIPTION
**Pull request by j143**
_what is going to be here?_
1. After the merging of #714 , here the `(matrix, matrix)` or `(matrix,scalar)` support will be added for `AND`, `NOT` and `OR`
2.  the unit tests will be added for these.

### CODE REVIEW

**Comment by akchinSTC** [comment]
Build failed, see build log for details

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2227/<h2>Failed Tests: <span class='status-failure'>9</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2227/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>9</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2227/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.jmlc/MulticlassSVMScoreTest/testJMLCMulticlassScoreSparse/'><strong>org.apache.sysml.test.integration.functions.jmlc.MulticlassSVMScoreTest.testJMLCMulticlassScoreSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2227/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.reorg/FullReverseTest/testReverseVectorSparseMR/'><strong>org.apache.sysml.test.integration.functions.reorg.FullReverseTest.testReverseVectorSparseMR</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2227/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.reorg/FullReverseTest/testReverseVectorSparseSP/'><strong>org.apache.sysml.test.integration.functions.reorg.FullReverseTest.testReverseVectorSparseSP</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2227/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.reorg/FullReverseTest/testReverseVectorDenseMR/'><strong>org.apache.sysml.test.integration.functions.reorg.FullReverseTest.testReverseVectorDenseMR</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2227/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.reorg/FullReverseTest/testReverseVectorDenseSP/'><strong>org.apache.sysml.test.integration.functions.reorg.FullReverseTest.testReverseVectorDenseSP</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2227/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.reorg/FullReverseTest/testReverseMatrixSparseMR/'><strong>org.apache.sysml.test.integration.functions.reorg.FullReverseTest.testReverseMatrixSparseMR</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2227/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.reorg/FullReverseTest/testReverseMatrixSparseSP/'><strong>org.apache.sysml.test.integration.functions.reorg.FullReverseTest.testReverseMatrixSparseSP</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2227/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.reorg/FullReverseTest/testReverseMatrixDenseMR/'><strong>org.apache.sysml.test.integration.functions.reorg.FullReverseTest.testReverseMatrixDenseMR</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2227/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.reorg/FullReverseTest/testReverseMatrixDenseSP/'><strong>org.apache.sysml.test.integration.functions.reorg.FullReverseTest.testReverseMatrixDenseSP</strong></a></li></ul>

**Comment by mboehm7** [comment]
with #714 this is already working (I still have to do some cleanups to nicely integrate NOT) but maybe you can use this PR to add further tests for scalar-matrix, matrix-scalar combinations.

**Comment by j143** [comment]
Hi @mboehm7 , I will keep this pr open until I complete my other jira, and will handle scalar-scalar, matrix-scalar tests later.

**Comment by j143** [comment]
log: 
```
org.apache.sysml.runtime.DMLRuntimeException: org.apache.sysml.runtime.DMLRuntimeException: ERROR: Runtime error in program block generated from statement block between lines 22 and 27 -- Error evaluating instruction: SPARK°write°false·SCALAR·BOOLEAN·true°target/testTemp/functions/binary/scalar/LogicalTest/out/C·SCALAR·STRING·true°textcell·SCALAR·STRING·true°·SCALAR·STRING·true
	at org.apache.sysml.runtime.controlprogram.Program.execute(Program.java:125)
	at org.apache.sysml.api.ScriptExecutorUtils.executeRuntimeProgram(ScriptExecutorUtils.java:102)
	at org.apache.sysml.api.DMLScript.execute(DMLScript.java:747)
	at org.apache.sysml.api.DMLScript.executeScript(DMLScript.java:511)
	at org.apache.sysml.api.DMLScript.main(DMLScript.java:238)
	at org.apache.sysml.test.integration.AutomatedTestBase.runTest(AutomatedTestBase.java:1222)
	at org.apache.sysml.test.integration.functions.binary.scalar.LogicalTest.runLogical(LogicalTest.java:180)
	at org.apache.sysml.test.integration.functions.binary.scalar.LogicalTest.testAndDenseCP(LogicalTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.apache.sysml.runtime.DMLRuntimeException: ERROR: Runtime error in program block generated from statement block between lines 22 and 27 -- Error evaluating instruction: SPARK°write°false·SCALAR·BOOLEAN·true°target/testTemp/functions/binary/scalar/LogicalTest/out/C·SCALAR·STRING·true°textcell·SCALAR·STRING·true°·SCALAR·STRING·true
	at org.apache.sysml.runtime.controlprogram.ProgramBlock.executeSingleInstruction(ProgramBlock.java:294)
	at org.apache.sysml.runtime.controlprogram.ProgramBlock.executeInstructions(ProgramBlock.java:218)
	at org.apache.sysml.runtime.controlprogram.ProgramBlock.execute(ProgramBlock.java:163)
	at org.apache.sysml.runtime.controlprogram.Program.execute(Program.java:118)
	... 39 more
Caused by: org.apache.sysml.runtime.DMLRuntimeException: Failed to obtain RDD for data type other than matrix or frame.
	at org.apache.sysml.runtime.controlprogram.context.SparkExecutionContext.getRDDHandleForVariable(SparkExecutionContext.java:325)
	at org.apache.sysml.runtime.instructions.spark.WriteSPInstruction.processFrameWriteInstruction(WriteSPInstruction.java:237)
	at org.apache.sysml.runtime.instructions.spark.WriteSPInstruction.processInstruction(WriteSPInstruction.java:145)
	at org.apache.sysml.runtime.controlprogram.ProgramBlock.executeSingleInstruction(ProgramBlock.java:264)
	... 42 more
org.apache.sysml.api.DMLException: org.apache.sysml.runtime.DMLRuntimeException: org.apache.sysml.runtime.DMLRuntimeException: ERROR: Runtime error in program block generated from statement block between lines 22 and 27 -- Error evaluating instruction: SPARK°write°false·SCALAR·BOOLEAN·true°target/testTemp/functions/binary/scalar/LogicalTest/out/C·SCALAR·STRING·true°textcell·SCALAR·STRING·true°·SCALAR·STRING·true
	at org.apache.sysml.api.DMLScript.executeScript(DMLScript.java:538)
	at org.apache.sysml.api.DMLScript.main(DMLScript.java:238)
	at org.apache.sysml.test.integration.AutomatedTestBase.runTest(AutomatedTestBase.java:1222)
	at org.apache.sysml.test.integration.functions.binary.scalar.LogicalTest.runLogical(LogicalTest.java:180)
	at org.apache.sysml.test.integration.functions.binary.scalar.LogicalTest.testAndDenseCP(LogicalTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.apache.sysml.runtime.DMLRuntimeException: org.apache.sysml.runtime.DMLRuntimeException: ERROR: Runtime error in program block generated from statement block between lines 22 and 27 -- Error evaluating instruction: SPARK°write°false·SCALAR·BOOLEAN·true°target/testTemp/functions/binary/scalar/LogicalTest/out/C·SCALAR·STRING·true°textcell·SCALAR·STRING·true°·SCALAR·STRING·true
	at org.apache.sysml.runtime.controlprogram.Program.execute(Program.java:125)
	at org.apache.sysml.api.ScriptExecutorUtils.executeRuntimeProgram(ScriptExecutorUtils.java:102)
	at org.apache.sysml.api.DMLScript.execute(DMLScript.java:747)
	at org.apache.sysml.api.DMLScript.executeScript(DMLScript.java:511)
	... 36 more
Caused by: org.apache.sysml.runtime.DMLRuntimeException: ERROR: Runtime error in program block generated from statement block between lines 22 and 27 -- Error evaluating instruction: SPARK°write°false·SCALAR·BOOLEAN·true°target/testTemp/functions/binary/scalar/LogicalTest/out/C·SCALAR·STRING·true°textcell·SCALAR·STRING·true°·SCALAR·STRING·true
	at org.apache.sysml.runtime.controlprogram.ProgramBlock.executeSingleInstruction(ProgramBlock.java:294)
	at org.apache.sysml.runtime.controlprogram.ProgramBlock.executeInstructions(ProgramBlock.java:218)
	at org.apache.sysml.runtime.controlprogram.ProgramBlock.execute(ProgramBlock.java:163)
	at org.apache.sysml.runtime.controlprogram.Program.execute(Program.java:118)
	... 39 more
Caused by: org.apache.sysml.runtime.DMLRuntimeException: Failed to obtain RDD for data type other than matrix or frame.
	at org.apache.sysml.runtime.controlprogram.context.SparkExecutionContext.getRDDHandleForVariable(SparkExecutionContext.java:325)
	at org.apache.sysml.runtime.instructions.spark.WriteSPInstruction.processFrameWriteInstruction(WriteSPInstruction.java:237)
	at org.apache.sysml.runtime.instructions.spark.WriteSPInstruction.processInstruction(WriteSPInstruction.java:145)
	at org.apache.sysml.runtime.controlprogram.ProgramBlock.executeSingleInstruction(ProgramBlock.java:264)
	... 42 more
Duration: 4126ms

java.lang.AssertionError: failed to run script ./src/test/scripts/functions/binary/scalar/LogicalAndTest.dml
exception: org.apache.sysml.api.DMLException: org.apache.sysml.runtime.DMLRuntimeException: org.apache.sysml.runtime.DMLRuntimeException: ERROR: Runtime error in program block generated from statement block between lines 22 and 27 -- Error evaluating instruction: SPARK°write°false·SCALAR·BOOLEAN·true°target/testTemp/functions/binary/scalar/LogicalTest/out/C·SCALAR·STRING·true°textcell·SCALAR·STRING·true°·SCALAR·STRING·true
message: org.apache.sysml.runtime.DMLRuntimeException: org.apache.sysml.runtime.DMLRuntimeException: ERROR: Runtime error in program block generated from statement block between lines 22 and 27 -- Error evaluating instruction: SPARK°write°false·SCALAR·BOOLEAN·true°target/testTemp/functions/binary/scalar/LogicalTest/out/C·SCALAR·STRING·true°textcell·SCALAR·STRING·true°·SCALAR·STRING·true
stack trace:
>org.apache.sysml.api.DMLScript.executeScript(DMLScript.java:538)
>org.apache.sysml.api.DMLScript.main(DMLScript.java:238)
>org.apache.sysml.test.integration.AutomatedTestBase.runTest(AutomatedTestBase.java:1222)
>org.apache.sysml.test.integration.functions.binary.scalar.LogicalTest.runLogical(LogicalTest.java:180)
>org.apache.sysml.test.integration.functions.binary.scalar.LogicalTest.testAndDenseCP(LogicalTest.java:60)
>sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>java.lang.reflect.Method.invoke(Method.java:498)
>org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
>org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
>org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
>org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
>org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
>org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
>org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
>org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
>org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
>org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
>org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
>org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
>org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
>org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
>org.junit.runners.ParentRunner.run(ParentRunner.java:309)
>org.junit.runners.Suite.runChild(Suite.java:127)
>org.junit.runners.Suite.runChild(Suite.java:26)
>org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
>org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
>org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
>org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
>org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
>org.junit.runners.ParentRunner.run(ParentRunner.java:309)
>org.junit.runner.JUnitCore.run(JUnitCore.java:160)
>com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
>com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
>com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
>com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.sysml.test.integration.AutomatedTestBase.runTest(AutomatedTestBase.java:1242)
	at org.apache.sysml.test.integration.functions.binary.scalar.LogicalTest.runLogical(LogicalTest.java:180)
	at org.apache.sysml.test.integration.functions.binary.scalar.LogicalTest.testAndDenseCP(LogicalTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2244/<h2>Failed Tests: <span class='status-failure'>6</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2244/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>6</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2244/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.binary.scalar/LogicalTest/testAndSparseCP/'><strong>org.apache.sysml.test.integration.functions.binary.scalar.LogicalTest.testAndSparseCP</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2244/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.binary.scalar/LogicalTest/testAndSparseMR/'><strong>org.apache.sysml.test.integration.functions.binary.scalar.LogicalTest.testAndSparseMR</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2244/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.binary.scalar/LogicalTest/testAndSparseSP/'><strong>org.apache.sysml.test.integration.functions.binary.scalar.LogicalTest.testAndSparseSP</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2244/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.binary.scalar/LogicalTest/testAndDenseCP/'><strong>org.apache.sysml.test.integration.functions.binary.scalar.LogicalTest.testAndDenseCP</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2244/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.binary.scalar/LogicalTest/testAndDenseMR/'><strong>org.apache.sysml.test.integration.functions.binary.scalar.LogicalTest.testAndDenseMR</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2244/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.binary.scalar/LogicalTest/testAndDenseSP/'><strong>org.apache.sysml.test.integration.functions.binary.scalar.LogicalTest.testAndDenseSP</strong></a></li></ul>

**Comment by mboehm7** [comment]
LGTM - thanks @j143

**Pull request closed without merging**
