### PR TITLE
Documentation for Multinomial Logistic Regression using Trust Region method

### PR DESCRIPTION
**Pull request by t201**
This Documentation is for Multinomial Logistic Regression using Trust Region method .

[Multilogreg Function.txt](https://github.com/apache/systemml/files/4744955/Multilogreg.Function.txt)

### CODE REVIEW

**Comment by t201** [comment]
Working on forming an example.Some of the things i'm not able to comprehend in the example given for reference-
-cbind
-scaling and shifting of columns to mean 0 and variance 1
-converting Y into indicator matrix
-! converge and ! innerconverge

**Comment by j143** [comment]
That's an improvement!
Now, let us work on example.

**Comment by t201** [comment]
Alright

**Comment by t201** [comment]
Updated the file with example .

**Comment by j143** [comment]
Thank you, @h0901 - LGTM. 👍 
🎉 🚀

**Pull request closed without merging**
