### PR TITLE
[SYSTEMML-1942] Enable conditional spark tests

### PR DESCRIPTION
**Pull request by gweidner**
Removed condition from multiple spark tests in functions.unary.matrix package  to enable successful run with additional config setup.

### CODE REVIEW

**Comment by gweidner** [comment]
Verified newly enabled tests ran successfully on local dev machine plus all tests passed for entire tests suite at [on demand build 330](https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/330/).  Also included style modifications based on changes observed for [SVDFactorizeTest](https://github.com/apache/systemml/blob/1d83cedb7c569d8fd9571e6f76d502e1e622ed02/src/test/java/org/apache/sysml/test/integration/functions/unary/matrix/SVDFactorizeTest.java).

**Comment by mboehm7** [comment]
LGTM - thanks @gweidner.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2146/

**Comment by gweidner** [comment]
Thank you Matthias!  I will merge.

**Pull request closed without merging**
