### PR TITLE
[SYSTEMML-2066] JMLC test for candidate exploration with unknowns

### PR DESCRIPTION
**Pull request by j143-zz**
_what is here?_
1. A test for JMLC, enabled codegen and dyn_recompile

_Questions_
-- sorry for these silly questions.
1. The codegen through JMLC, working the same way as in the normal case.
2. what are the candidates, unary and matrix-scalar are already in our codegen, right?

Thanks, Matthias.

### CODE REVIEW

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2308/

**Comment by j143** [comment]
Test this Jenkins

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2309/

**Comment by j143** [comment]
Hi @mboehm7 , can you help me the next step here.

**Comment by mboehm7** [comment]
@j143 thanks for starting work on this but note that you should not change the JMLC configuration. Instead of simply enabling dynamic recompilation (which already allows to use codegen through JMLC), the task is to provide an additional codegen compilation mode that only compiles "safe" fused operators which don't need sizes for validity checks. Hence, I would recommend to initially add a configuration to `SpoofCompiler`, and modify the OFMC conditions in `TemplateCell`, `TemplateOuterProduct`, and `TemplateRow` to respect this configuration and only allow candidates that don't rely on sizes (e.g., unary and matrix-scalar operations as well as aggregations).

**Comment by j143** [comment]
w/o `LOG`, candidate:
```
public final class TMP2 extends SpoofCellwise {
  public TMP2() {
    super(CellType.NO_AGG, false, null);
  }
  protected double genexec(double a, SideInput[] b, double[] scalars, int m, int n, int rix, int cix) { 
    double TMP0 = Math.log(a);
    double TMP1 = FastMath.exp(TMP0);
    return TMP1;
  }
}
```
w/o `LOG` closes:
```
public final class TMP4 extends SpoofRowwise { 
  public TMP4() {
    super(RowType.NO_AGG, -1, false, 2);
  }
  protected void genexec(double[] a, int ai, SideInput[] b, double[] scalars, double[] c, int ci, int len, int rix) { 
    double[] TMP0 = LibSpoofPrimitives.vectLogWrite(a, ai, len);
    double[] TMP1 = LibSpoofPrimitives.vectExpWrite(TMP0, 0, TMP0.length);
    LibSpoofPrimitives.vectWrite(TMP1, c, ci, TMP1.length);
  }
  protected void genexec(double[] avals, int[] aix, int ai, SideInput[] b, double[] scalars, double[] c, int ci, int alen, int len, int rix) { 
    double[] TMP2 = LibSpoofPrimitives.vectLogWrite(avals, aix, ai, alen, len);
    double[] TMP3 = LibSpoofPrimitives.vectExpWrite(TMP2, 0, TMP2.length);
    LibSpoofPrimitives.vectWrite(TMP3, c, ci, TMP3.length);
  }
}
```

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2316/

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2317/<h2>Failed Tests: <span class='status-failure'>3</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2317/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>3</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2317/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.codegen/MiscPatternTest/testCodegenMisc2CP/'><strong>org.apache.sysml.test.integration.functions.codegen.MiscPatternTest.testCodegenMisc2CP</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2317/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.codegen/MiscPatternTest/testCodegenMisc2SP/'><strong>org.apache.sysml.test.integration.functions.codegen.MiscPatternTest.testCodegenMisc2SP</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2317/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.codegen/MiscPatternTest/testCodegenMiscRewrite2CP/'><strong>org.apache.sysml.test.integration.functions.codegen.MiscPatternTest.testCodegenMiscRewrite2CP</strong></a></li></ul>

**Comment by j143** [comment]
Hi @mboehm7 , Did I understand the task?. Please, once verify the outcome. Thanks.

**Comment by mboehm7** [comment]
No, unfortunately not. Most importantly, please ensure that for normal operations not a single aspect of the codegen compilation semantics should change. 

Furthermore, don't focus on individual operations but classes of operations. To do so, think about what the problem is with unkowns. On example are binary operations like A+B+C - normally we would order the inputs according to dimensions and then non-zeros. However, if we order C, A, B and C is a column vector while A and B are matrices, the generated operator would produce incorrect results. Without recompilation we could not correct that.

**Pull request closed without merging**
