### PR TITLE
[SYSTEMML-1756] Potential infinite recursion in Explain#explain(DMLProgram, Program, ExplainType)

### PR DESCRIPTION
**Pull request by tedyu**
Pass null for ExplainCounts parameter

### CODE REVIEW

**Comment by akchinSTC** [comment]
Can an Admin verify this patch?

**Comment by deroneriksson** [comment]
Test this Jenkins

**Comment by deroneriksson** [comment]
add to whitelist.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1736/

**Comment by deroneriksson** [comment]
LGTM. Thank you @tedyu

**Pull request closed without merging**
