### PR TITLE
[SYSTEMML-1978] Add PCA to Performance Test Suite

### PR DESCRIPTION
**Pull request by krishnakalyan3**
Original [JIRA](https://issues.apache.org/jira/browse/SYSTEMML-1978)

Made changed to perf test suit to include PCA .

### CODE REVIEW

**Comment by krishnakalyan3** [comment]
ping @nakul02 could you please review this PR?.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2215/

**Comment by nakul02** [comment]
This looks fine. What sizes have you tested this out with?

**Comment by krishnakalyan3** [comment]
I have tested on 10k_100, 50k_100, 100k_100, 100k_100, 10k_1k. Results below

```
➜  python git:(pca_perf) ✗ ./run_perftest.py --family dimreduction --file-system-type local --exec-type singlenode --mat-shape 10k_100
dimreduction,data-gen,none,dense,10k_100,0.401
PCA.dimreduction,train,none,10k_100,dense,0.658
➜  python git:(pca_perf) ✗ ./run_perftest.py --family dimreduction --file-system-type local --exec-type singlenode --mat-shape 50k_100
dimreduction,data-gen,none,dense,50k_100,1.049
PCA.dimreduction,train,none,50k_100,dense,1.166
➜  python git:(pca_perf) ✗ ./run_perftest.py --family dimreduction --file-system-type local --exec-type singlenode --mat-shape 100k_100
dimreduction,data-gen,none,dense,100k_100,1.630
PCA.dimreduction,train,none,100k_100,dense,1.711
➜  python git:(pca_perf) ✗ ./run_perftest.py --family dimreduction --file-system-type local --exec-type singlenode --mat-shape 10k_1k  
dimreduction,data-gen,none,dense,10k_1k,1.447
PCA.dimreduction,train,none,10k_1k,dense,18.417
```

**Pull request closed without merging**
