### PR TITLE
[SYSTEMML-1891] Prevent 'Script string is blank' exception for Python…

### PR DESCRIPTION
**Pull request by gweidner**
… toNumPy()

### CODE REVIEW

**Comment by gweidner** [comment]
With this change, the expected results was observed for both toNumPy() and toPandas():
`
result.toNumPy()
SystemML Statistics:
Total execution time:  0.017 sec.
Number of executed Spark inst: 2.

array([[-60.],
       [-60.],
       [-60.]])
`

**Comment by gweidner** [comment]
This is a quick work-around but I'm open to suggestions for better way or location to ensure non-blank script string.
cc @niketanpansare @asurve

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2054/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2054/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2054/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.parfor/ParForBlockwiseDataPartitioningTest/testParForColBlockPartitioningRemoteLocalSparseNegative/'><strong>org.apache.sysml.test.integration.functions.parfor.ParForBlockwiseDataPartitioningTest.testParForColBlockPartitioningRemoteLocalSparseNegative</strong></a></li></ul>

**Comment by gweidner** [comment]
Note this change also resolved similar "Script string is blank" exception test failures for test_matrix_agg_fn.py and test_matrix_binary_op.py under src/main/python/tests.  The single test failure reported for corresponding pull request build is not applicable.

**Comment by gweidner** [comment]
Resolved by https://github.com/apache/systemml/pull/659.

**Pull request closed without merging**
