### PR TITLE
[MINOR] fix for SYSTEMML_1795

### PR DESCRIPTION
**Pull request by nakul02**
The GPUContextPool.AVAILABLE_GPUS is read after the lops are
constructed, but the value needs to be read before. This patch is a fix
that problem.

Ping @niketanpansare - can you please review & test this?

### CODE REVIEW

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1801/

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1805/

**Comment by niketanpansare** [comment]
Thanks @nakul02 .. I have tested this on spark-nvidia and it works perfectly. LGTM 👍

**Comment by nakul02** [comment]
Thanks @niketanpansare for the review. Will merge.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1813/

**Pull request closed without merging**
