### PR TITLE
[SYSTEMML-658] Setting scalar strings not automatically treated as strings by JMLC

### PR DESCRIPTION
**Pull request by j143**
_What is here?_
Scalar strings are automatically treated as strings with recent development by JMLC.

Hence, I am adding a test. @deroneriksson

### CODE REVIEW

**Comment by j143** [comment]
Can the four data files above be reverted, they happened to be converted to CRLF on by windows machine.
Thanks.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2303/

**Comment by j143** [comment]
Hi @mboehm7 , this one seems good. Thanks.

**Comment by deroneriksson** [comment]
LGTM, thanks @j143.

When I merge, I'll add a conn.close() line to the end of the test method since Connection implements Closeable.

**Pull request closed without merging**
