### PR TITLE
[SYSTEMML-1185][SYSTEMML-1766] Add experimental breast cancer code

### PR DESCRIPTION
**Pull request by dusenberrymw**
This adds additional code from the experimental breast cancer branch to the main repo, and cleans up existing files.

### CODE REVIEW

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1743/

**Comment by deroneriksson** [comment]
Test this Jenkins

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1746/

**Comment by deroneriksson** [comment]
Looks like the rat license check hangs. Could you try adding `<exclude>**/*.svg</exclude>` to the rat excludes in the pom.xml file and see if that fixes it?

**Comment by deroneriksson** [comment]
At the top of each *.ipynb page, do you think it would be a good idea to include a link to https://github.com/apache/systemml/blob/master/LICENSE?

**Comment by deroneriksson** [comment]
LGTM once the rat license check doesn't hang.

**Comment by bertholdreinwald** [comment]
i would think so.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1753/

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1769/

**Pull request closed without merging**
