### PR TITLE
[WIP][SYSTEMML-2110] Codegen support for relu operation

### PR DESCRIPTION
**Pull request by j143**
`(X > 0) * Y`,  integration support for codegeneration.

1. spoof primitives.
2. tests

**Question**
But, how `libmatrixDNN` class's operator can be invoked, is it a rewrite or is there any function name such as `relu_backward()` .

### CODE REVIEW

**Comment by j143** [comment]
Sorry, I will try to map the expression to >, * operators instead of a primitive operator. Thanks.

**Comment by mboehm7** [comment]
well right, there is no need for any of these extensions - just add the tests and a TODO comment to `BinaryOp.constructLopsBinaryDefault` (line 662) to remove RELU_BACKWARD once codegen is supported for GPUs as well. The reason is that relu_backward was not added as a hop rewrite but a hop-lop rewrite, which means its not even visible during codegen.

**Comment by j143** [comment]
Hi @mboehm7 , the tests here seem to give wrong result to me, wrt R scripts.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2276/

**Comment by mboehm7** [comment]
yes, the reason is that we use a row-wise default reshape while R uses a column-wise reshape. This was a conscious decision because we internally use row-major representations while R uses column-major formats. You can simply use fix your R script via 
`X = matrix(seq(1, 6000)/600, 300, 20, byrow=TRUE);`
instead of 
`X = matrix(seq(1, 6000)/600, 300, 20);`

While you are at it, could you also remove the other merged changes. Thanks.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2278/

**Comment by mboehm7** [comment]
LGTM - thanks @j143

**Pull request closed without merging**
