### PR TITLE
[SYSTEMML-1426] Add support for built-in functions ceiling and ceil

### PR DESCRIPTION
**Pull request by gweidner**
Renamed built-in function `ceil` to `ceiling` to be more consistent with R.
Also updated existing dml scripts to use `ceiling.`

### CODE REVIEW

**Comment by gweidner** [comment]
Verified unit tests passed prior to opening PR:
[On Demand 329](https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/329/)

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2137/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2137/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2137/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.recompile/IPAConstantPropagationTest/testConstantPropagationNoUpdateBranchRemovalNoIPA/'><strong>org.apache.sysml.test.integration.functions.recompile.IPAConstantPropagationTest.testConstantPropagationNoUpdateBranchRemovalNoIPA</strong></a></li></ul>

**Comment by mboehm7** [comment]
In general, this looks very good @gweidner, but I would recommend to leave the internal compiler/runtime constants and opcodes as they are (i.e., CEIL) in favor of brevity. Also, we might want to support both "ceiling" and "ceil" (we can map both to the internal ceil in BuiltinFunctionExpression). Just out of curiosity, I double checked R and SparkR: ceiling is the base function in R but there are R packages that define ceil as an alias too; SparkR also supports both.

**Comment by gweidner** [comment]
Thank you for reviewing Matthias!  Supporting both ceil and ceiling is a great idea so I'll make corresponding updates here and use `ceil` as opcode.

**Comment by niketanpansare** [comment]
+1 for supporting both ceiling as well as ceil.

**Comment by gweidner** [comment]
Thank you Niketan!  I'll also plan on updating python defmatrix.py to support both as well.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2140/

**Comment by gweidner** [comment]
I've restored `ceil` built-in function and added `ceiling` with both mapped to same existing opcode which helped reduce scope of changes (thank you @mboehm7 for recommending).  Kept existing dml scripts as-is (i.e., use `ceil`).  Updated python matrix to allow both `ceil` and `ceiling`.

Added new test cases/script for `ceiling` but only under `RUNTIME_PLATFORM.HYBRID` mode since RoundTests disabled for `SPARK`.  Verified RoundTest and CPlanVectorPrimitivesTest locally and full tests passed in referenced PR build.  Manually tested python matrix in pyspark shell:

`t = m1.ceil()
t
# This matrix (mVar3) is backed by below given PyDML script (which is not yet evaluated). To fetch the data of this matrix, invoke toNumPy() or toDF() or toPandas() methods.
mVar1 = load(" ", format="csv")
mVar3 = ceil(mVar1)
save(mVar3, " ")

t.toDF()
SystemML Statistics:
Total execution time:           0.015 sec.
Number of executed Spark inst:  1.

DataFrame[C0: double, C1: double, C2: double]

t2 = m2.ceiling()
t2
# This matrix (mVar4) is backed by below given PyDML script (which is not yet evaluated). To fetch the data of this matrix, invoke toNumPy() or toDF() or toPandas() methods.
mVar2 = load(" ", format="csv")
mVar4 = ceiling(mVar2)
save(mVar4, " ")`

**Comment by mboehm7** [comment]
LGTM - thanks @gweidner. In a subsequent change, we should cleanup these tests you mentioned. These conditional tests are from a time when we did not pull in Spark by default. We should make them all unconditional and add the necessary spark setup (similar to all the other tests) where required.

**Comment by gweidner** [comment]
Thank you @mboehm7 for approving!  I'll merge this one and address the conditional test cases in separate JIRA/PR.

**Pull request closed without merging**
