### PR TITLE
[SYSTEMML-1974] Implement Optim test functions (multiple local minima, part 1)

### PR DESCRIPTION
**Pull request by j143**
Hi, once we implement the optimization script, we would like to test those.
 
So, this one introduces some multiple local minima functions, as a first iteration for easier review. This library will help us hard test our optimization scripts, nn etc. for the function approximation. 

please share feedback on 
1. naming convention of the functions. - @deroneriksson 
2. review for the syntax, loops. - @mboehm7 @niketanpansare

### CODE REVIEW

**Comment by niketanpansare** [comment]
It is difficult to stare at the script and see how it fits into SystemML especially because the feature you are working on is rather complicated. Can you please batch your PR such that every PR has a test or a demo that a non-domain expert can try to understand the utility as well as correctness of the script/feature you want to merge ?

**Comment by j143** [comment]
Hi @niketanpansare , please find this [link](https://www.sfu.ca/~ssurjano/stybtang.html). Here, I am implementing this type of functions.

s-tang-fun

For example, we have a neural network or an optimization algorithm. So,
1. we take one function (say  Styblinski-Tang function), (first fig. from left )  
2. we give input & output values of this function to the network(2 & 3 fig. from left are the networks trained on regular batching & sobolev kind of training after 20 trains), to see how well our function is being approximated (here, sobolev network approximated styblinski-Tang to a reasonable accuracy).
3. These functions are necessary to check all the nuts & bolts of the network are sound enough.

fun-description

**Comment by j143** [comment]
@dusenberrymw - please correct me if I am wrong with the above comment.

As these are the normal functions, may be the one way to test these will be running the script, and then make plot some how, and then see whether the function is correct. Please advice on how to test this.

**Comment by niketanpansare** [comment]
1. You can consider running following Python code to get y and x:
```python
from systemml import MLContext, dml, dmlFromResource, dmlFromFile, dmlFromUrl
ml = MLContext(spark)
s = """ 
source("many_local_minima.dml") as fn;
a = 20.0; b = 0.2; c = 2 * 3.1415
d = ??
x = rand(rows=1, cols=d)
y = fn::Ackley(x, a, b, c)
"""
helloScript = dml('source("many_local_minima.dml") as fn; y= fn::Ackley()').output('x', 'y')
res = ml.execute(helloScript)
xMat, yMAt = res.get('x', 'y')
x = xMat.toNumpy()
y = yMat.toNumpy()
```

2. Then you can plot them using the code mentioned in https://matplotlib.org/examples/mplot3d/subplot3d_demo.html

3. Paste the generated plots in the PR (and may be with expected plots) to show that the functions are working correctly :)

**Comment by j143** [comment]
Can anyone help me understand, why all the above commits are added, I believe I have rebased my branch before committing & everything is fine yesterday.!

**Comment by dusenberrymw** [comment]
@j143 It looks like there was a forced update to the master branch last night that wiped out the half of month worth of commits, which are now showing up in this PR.  Don't worry about it, as soon as the master branch is fixed, this PR will look fine again.

**Comment by j143** [comment]
Hi, I ran the above script. But, till 
```
>> xMat
Matrix
>>yMat
2.790
>>X = xMat.toNumpy()
Attribute Error: 'matrix' object has no attribute 'toNumpy'
>>y = xMat.toNumpy()
Attribute Error: 'float' object has no attribute 'toNumpy'
```
And in the Matplotlib, here
```
X = np.arange(-5, 5, 0.25)
Y = np.arange(-5, 5, 0.25)
X, Y = np.meshgrid(X, Y)
R = np.sqrt(X**2 + Y**2)
Z = np.sin(R)
surf = ax.plot_surface(X, Y, Z, rstride=1, cstride=1, cmap=cm.coolwarm,
                       linewidth=0, antialiased=False)
ax.set_zlim(-1.01, 1.01)
fig.colorbar(surf, shrink=0.5, aspect=10)
```
how to arrange X, Y values. as for `x = rand(rows=1, cols=d)`, first column will form `X` & the second column `Y` as input. And along the z-axis value of `y = fn::Ackley(X, a, b, c)`

If possible can you run the script for `Ackley`, to check that it works for me too. cc @niketanpansare

**Comment by j143** [comment]
ping for help. - @niketanpansare. Please find the above comment.

**Comment by niketanpansare** [comment]
Can you please try `X = xMat.toNumPy()` ?

**Comment by j143** [comment]
Hi, how can I output the a `y` matrix, to a `csv` file and where that file will be saved. Thanks.
```
windows OS
only spark-submit works
```

**Comment by niketanpansare** [comment]
Please see https://docs.scipy.org/doc/numpy/reference/generated/numpy.savetxt.html

**Comment by akchinSTC** [comment]
Build triggered. sha1 is merged.

**Comment by akchinSTC** [comment]
Build started sha1 is merged.

**Comment by akchinSTC** [comment]
Build failed, see build log for details

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2224/<h2>Failed Tests: <span class='status-failure'>8</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2224/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>8</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2224/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.jmlc/MulticlassSVMScoreTest/testJMLCMulticlassScoreSparseFlags/'><strong>org.apache.sysml.test.integration.functions.jmlc.MulticlassSVMScoreTest.testJMLCMulticlassScoreSparseFlags</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2224/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.applications.parfor/ParForUnivariateStatsTest/testForUnivariateStatsSerialSerialMR/'><strong>org.apache.sysml.test.integration.applications.parfor.ParForUnivariateStatsTest.testForUnivariateStatsSerialSerialMR</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2224/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.parfor/ParForRulebasedOptimizerTest/testParForRulebasedOptimizerBivariateStatsSmallSmall/'><strong>org.apache.sysml.test.integration.functions.parfor.ParForRulebasedOptimizerTest.testParForRulebasedOptimizerBivariateStatsSmallSmall</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2224/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.parfor/ParForRulebasedOptimizerTest/testParForHeuristicOptimizerBivariateStatsSmallSmall/'><strong>org.apache.sysml.test.integration.functions.parfor.ParForRulebasedOptimizerTest.testParForHeuristicOptimizerBivariateStatsSmallSmall</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2224/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.parfor/ParForRulebasedOptimizerTest/testParForRulebasedOptimizerBivariateStatsLargeLarge/'><strong>org.apache.sysml.test.integration.functions.parfor.ParForRulebasedOptimizerTest.testParForRulebasedOptimizerBivariateStatsLargeLarge</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2224/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.parfor/ParForRulebasedOptimizerTest/testParForRulebasedOptimizerBivariateStatsLargeSmall/'><strong>org.apache.sysml.test.integration.functions.parfor.ParForRulebasedOptimizerTest.testParForRulebasedOptimizerBivariateStatsLargeSmall</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2224/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.parfor/ParForRulebasedOptimizerTest/testParForHeuristicOptimizerBivariateStatsLargeLarge/'><strong>org.apache.sysml.test.integration.functions.parfor.ParForRulebasedOptimizerTest.testParForHeuristicOptimizerBivariateStatsLargeLarge</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2224/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.parfor/ParForRulebasedOptimizerTest/testParForHeuristicOptimizerBivariateStatsLargeSmall/'><strong>org.apache.sysml.test.integration.functions.parfor.ParForRulebasedOptimizerTest.testParForHeuristicOptimizerBivariateStatsLargeSmall</strong></a></li></ul>

**Pull request closed without merging**
