### PR TITLE
[SYSTEMML-1649, 1866][WIP] Add MLContext test class for GLM scripts

### PR DESCRIPTION
**Pull request by j143**
This adds a test class for all the operations and functions in `GLM.dml` and `GLM-predict.dml` scripts.

### CODE REVIEW

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2036/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2036/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2036/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMBinomialSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMBinomialSparse</strong></a></li></ul>

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2039/<h2>Failed Tests: <span class='status-failure'>6</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2039/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>6</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2039/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMGammaSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMGammaSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2039/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPoissonSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPoissonSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2039/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMGammaDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMGammaDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2039/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMBinomialSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMBinomialSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2039/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPoissonDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPoissonDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2039/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMBinomialDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMBinomialDense</strong></a></li></ul>

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2043/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2043/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2043/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPoissonSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPoissonSparse</strong></a></li></ul>

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2044/

**Comment by j143** [comment]
1. Test with `getRandomMatrix(2468, 1007, 0, 1, sparse?sparsity2:sparsity1, -1);`
```
23:45:04 Running org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest
23:45:04 Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.43 sec - in org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest
```
2. Test with `getRandomMatrix(10, 3, 0, 1, sparse?sparsity2:sparsity1, -1);`
```
failure at org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPoissonSparse(MLContextGLMTest.java:49)
```
```
BEGIN GLM SCRIPT
Reading X...
Reading Y...
BEGIN IRLS ITERATIONS...
Iter #1 completed, ||z|| = 0.0E0, trust_delta = 1.1006E0, reached = 0, ||g|| = 0.0E0, new_log_l = -InfinityE0, log_l_change = -InfinityE0, rho = 0.0E0
Iter #2 completed, ||z|| = 0.0E0, trust_delta = 2.7515E-1, reached = 0, ||g|| = 0.0E0, new_log_l = -InfinityE0, log_l_change = -InfinityE0, rho = 0.0E0
Iter #3 completed, ||z|| = 0.0E0, trust_delta = 6.8787E-2, reached = 0, ||g|| = 0.0E0, new_log_l = -InfinityE0, log_l_change = -InfinityE0, rho = 0.0E0
Iter #4 completed, ||z|| = 0.0E0, trust_delta = 1.7197E-2, reached = 0, ||g|| = 0.0E0, new_log_l = -InfinityE0, log_l_change = -InfinityE0, rho = 0.0E0
Iter #5 completed, ||z|| = 0.0E0, trust_delta = 4.2992E-3, reached = 0, ||g|| = 0.0E0, new_log_l = -InfinityE0, log_l_change = -InfinityE0, rho = 0.0E0
Did not converge.
Duration: 644ms
```

**Comment by j143** [comment]
cc @mboehm7 @deroneriksson 
I believe the test failed with little matrix, 'cause of the high sparsity.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2045/

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2050/

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2051/<h2>Failed Tests: <span class='status-failure'>6</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2051/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>6</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2051/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPredPoissonDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPredPoissonDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2051/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPredPoissonSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPredPoissonSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2051/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPredGammaSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPredGammaSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2051/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPredBinomialSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPredBinomialSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2051/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPredGammaDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPredGammaDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2051/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPredBinomialDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPredBinomialDense</strong></a></li></ul>

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2053/<h2>Failed Tests: <span class='status-failure'>6</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2053/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>6</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2053/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPredPoissonDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPredPoissonDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2053/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPredPoissonSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPredPoissonSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2053/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPredGammaSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPredGammaSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2053/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPredBinomialSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPredBinomialSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2053/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPredGammaDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPredGammaDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2053/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPredBinomialDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPredBinomialDense</strong></a></li></ul>

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2078/<h2>Failed Tests: <span class='status-failure'>6</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2078/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>6</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2078/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPredPoissonDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPredPoissonDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2078/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPredPoissonSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPredPoissonSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2078/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPredGammaSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPredGammaSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2078/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPredBinomialSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPredBinomialSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2078/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPredGammaDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPredGammaDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2078/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPredBinomialDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPredBinomialDense</strong></a></li></ul>

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2080/

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2081/<h2>Failed Tests: <span class='status-failure'>6</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2081/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>6</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2081/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPredPoissonDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPredPoissonDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2081/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPredPoissonSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPredPoissonSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2081/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPredGammaSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPredGammaSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2081/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPredBinomialSparse/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPredBinomialSparse</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2081/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPredGammaDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPredGammaDense</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2081/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext.algorithms/MLContextGLMTest/testGLMPredBinomialDense/'><strong>org.apache.sysml.test.integration.mlcontext.algorithms.MLContextGLMTest.testGLMPredBinomialDense</strong></a></li></ul>

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2172/

**Pull request closed without merging**
