### PR TITLE
[SYSTEMML-1808] [SYSTEMML-1658] Visualize Hop DAG for explaining the optimizer

### PR DESCRIPTION
**Pull request by niketanpansare**
This feature could be used in the external demos to explain the SystemML's compiler. It could also be used by beginners who might find it difficult to interpret our explain hop output. For advanced users, it doesnot provide any additional information over explain hop output (other than line numbers). Please note: it doesnot add any additional runtime overhead.

image

image

@deroneriksson @bertholdreinwald

### CODE REVIEW

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1811/

**Comment by niketanpansare** [comment]
After the latest commit, the generated DAG follows correct node ordering:

image

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1814/

**Comment by niketanpansare** [comment]
@deroneriksson @bertholdreinwald I would like to merge this PR today. Please let me know if there are any objections or concerns :)

**Comment by deroneriksson** [comment]
Please don't merge yet before I have reviewed.

**Comment by niketanpansare** [comment]
Sure :)

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1824/

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1826/

**Comment by niketanpansare** [comment]
@bertholdreinwald @mboehm7 @prithvirajsen @dusenberrymw I have added a new utility method `jvm_stdout` in our python API to display the output from Java. This feature is useful in notebook environment:

image

image

For long running jobs, please use the parameter `parallel_flush`:

image

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1832/

**Comment by niketanpansare** [comment]
ping @deroneriksson

**Comment by deroneriksson** [comment]
This is very extremely useful Niketan! Thank you for such a great contribution. LGTM with a couple comments:

1) Could the Java MLContext.getHopDag methods be moved to static MLContextUtil.getHopDag methods (and include an MLContext method parameter too to get the various settings) and called from the Python MLContext?
  My thinking:
  a) Output is in Python graphviz format which is used from python but not java/scala.
      Example: `digraph {h5[label="u(print)[1:0-1:19]", shape="octagon", color="yellow", tooltip="[-1 X -1], nnz=-1, mem= [in=0, inter=0, out=0 -> 0MB]"];
rankdir = "BT"}`
  b) MLContext Java class is very lightweight by design (notice how few parameters tend to exist on the MLContext method signatures). The MLContextUtil class tends to hold such code so far in the API.

2) Nice to have:
  a) Javadoc all methods if they're in the MLContext API (public facing code).
  b) Auto-format the MLContext API Java code with one of SystemML's code formats (in dev/code-style)

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1849/

**Comment by niketanpansare** [comment]
Thanks  @gweidner for testing this PR on your laptop.

Thanks @deroneriksson  ... addressed your concerns :+1:

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1855/

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1856/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1856/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1856/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.data/FullReblockTest/testBinaryBlockMultipleMSparseMR/'><strong>org.apache.sysml.test.integration.functions.data.FullReblockTest.testBinaryBlockMultipleMSparseMR</strong></a></li></ul>

**Pull request closed without merging**
