### PR TITLE
[SYSTEMML-1883] implement xor function

### PR DESCRIPTION
**Pull request by j143**
implementation of xor function.

### CODE REVIEW

**Comment by j143** [comment]
Test this Jenkins

**Comment by j143** [comment]
Hi @mboehm7 , this implementation is to take care of only simple `xor(op1, op2)` operation. 
BTW, how only to run this test `src/test/java/org/apache/sysml/test/integration/functions/binary/scalar/XorTest.java`, w/o `mvn verify`.

**Comment by mboehm7** [comment]
great - I'll have a look tomorrow. In the meantime, you can simply run your test or individual subtests via junit in your IDE.

**Comment by j143** [comment]
tested with `spark-submit target/SystemML.jar -f scripts/xor_test.dml` (please, remove this file in commit!)
```
xor of 1, 1 is 0
xor of 1, 0 is 1
xor of 0, 1 is 1
xor of 0, 0 is 0
SystemML Statistics:
Total execution time:           0.001 sec.
Number of executed Spark inst:  0.
```
I will try to add the bool string, matrix ones later on. Thanks.

**Comment by mboehm7** [comment]
LGTM - thanks @j143. FYI: while merging, I brought a modified version of your tests back in and did some minor cleanups.

**Pull request closed without merging**
