### PR TITLE
[SYSTEMML-1929] Update deploy-mode in sparkDML.sh and docs

### PR DESCRIPTION
**Pull request by gweidner**
Updated spark-submit description to use `--deploy-mode` instead of deprecated parameters and corrected batch mode copy/paste error.

### CODE REVIEW

**Comment by mboehm7** [comment]
Could we do the same for scripts/sparkDML.sh, incl the removal of `spark.akka.frameSize`?

**Comment by gweidner** [comment]
Good catch Matthias!  I'll add commit for sparkDML.sh to this PR too.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2118/

**Comment by gweidner** [comment]
I updated sparkDML.sh to use `--master yarn --deploy-mode client` as default and removed 
`--conf spark.akka.frameSize=128`.  Also removed spark.akka.frameSize reference from recommended Spark configuration settings in spark-batch-mode and spark-mlcontext-programming-guide docs.

**Comment by gweidner** [comment]
Note although I removed `spark.akka.frameSize` from sparkDML.sh and recommended settings, I'm not sure if I should instead replace with `--conf spark.rpc.message.maxSize=128` since it also means:
"Maximum message size (in MB) to allow in "control plane" communication; generally only applies to map output size information sent between executors and the driver. Increase this if you are running jobs with many thousands of map and reduce tasks and see messages about the RPC message size."

**Comment by gweidner** [comment]
Applied similar changes to python performance test scripts.

**Comment by nakul02** [comment]
It turns out that we don't need to specify the `spark.akka.frameSize=128` or `spark.rpc.message.maxSize=128`. According to the documentation for [Spark 1.6 ](https://spark.apache.org/docs/1.6.1/configuration.html), that is already the default size. Also, in the current spark master, the [value defaults](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/util/RpcUtils.scala#L59) to 128.
I also discussed this in an offline conversation with @niketanpansare.

I think we should remove this parameters from all our scripts.

**Comment by nakul02** [comment]
For the python scripts, we'll need to pass the newly introduced `--deploy-mode` parameter to other parts of the script. 
Ping @krishnakalyan3.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2158/

**Comment by gweidner** [comment]
Thank you @nakul02 for reviewing and clarifying!  I've incorporated the comments where I similarly modified sparkDML.sh in src/main/resources/scripts and also updated all algorithms docs.  For the python performance scripts, I reverted the `--deploy-mode` parameter which can be addressed in a separate PR.

**Comment by krishnakalyan3** [comment]
I will start working on `deploy-mode` for `perf test suit`.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2159/

**Comment by gweidner** [comment]
I opened a separate JIRA (https://issues.apache.org/jira/browse/SYSTEMML-1945) which can be used for the performance test scripts.

**Pull request closed without merging**
