### PR TITLE
[SYSTEMML-1895] Jcuda for windows & linux (x86_64, ppc64le) are included in extra jar

### PR DESCRIPTION
**Pull request by nakul02**
Ping @niketanpansare, @bertholdreinwald, @asurve 

@gweidner, @deroneriksson - could you please review this?

### CODE REVIEW

**Comment by deroneriksson** [comment]
@nakul02 Usually it is good to avoid maven warnings if possible (although not always necessary). Perhaps you can work with @gweidner (who uses SystemML with Windows) to see if the warning can be removed?

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2059/

**Comment by gweidner** [comment]
I checked-out this pr (git systemml-pr 656) and successfully built distribution from command prompt shell.  I compared the console build results against master build results for windows dev environment and found no new warnings.  Note I ran the build outside of Eclipse and my installed maven version is 3.3.0.

**Comment by nakul02** [comment]
Awesome! Thanks @gweidner 
If there are no warnings, I will wait for @deroneriksson's and @gweidner's approval before merging.

**Comment by nakul02** [comment]
Thanks @gweidner!

**Comment by nakul02** [comment]
Licenses seem to be in order, I shall merge.

**Pull request closed without merging**
