### PR TITLE
[SYSTEMML-1820] Add isStatistics and isExplain to Python MLContext

### PR DESCRIPTION
**Pull request by gweidner**
Added methods isStatistics() and isExplain() for consistency with Scala MLContext.

### CODE REVIEW

**Comment by gweidner** [comment]
Tested with Pyspark (2.7):
`
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.1.0
      /_/

Using Python version 2.7.5 (default, Aug  2 2016 04:20:16)
SparkSession available as 'spark'.
>>> from systemml import MLContext
>>> ml = MLContext(spark)

Welcome to Apache SystemML!
Version 1.0.0-SNAPSHOT
>>> ml.isStatistics()
False
>>> ml.isExplain()
False
>>> ml.setStatistics(True)
MLContext
>>> ml.setExplain(True)
MLContext
>>> ml.isExplain()
True
>>> ml.isStatistics()
True
>>> exit()
`

Other minor inconsistencies to be addressed separately.

**Comment by deroneriksson** [comment]
LGTM. Tested with Python 3.5.2 and Spark 2.1.0.

**Comment by gweidner** [comment]
Thank you @deroneriksson for reviewing!

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1845/

**Pull request closed without merging**
