### PR TITLE
[SYSTEMML-1996] Main Bayesian Optimization script

### PR DESCRIPTION
**Pull request by j143**
_What is this?_
**Selecting the next point to evaluate**
_1._ Inputs `X`, `y`, are projected in to a `D`-dimensional hypercube, of them only `M` points will be sampled.
_2._ Now, with `X`, `y` we make a probablistic model `mode.dml`, `gpc.dml`, `gpr.dml`, where in we get a mean & variance values.

### CODE REVIEW

**Comment by j143** [comment]
Hi @niketanpansare , I this pr acts as a vantage points for all the features, & could help us see how each scripts could fit in.

**Comment by akchinSTC** [comment]
Build finished.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2232/

**Comment by niketanpansare** [comment]
At a high-level, this makes sense :+1:

**Pull request closed without merging**
