### PR TITLE
[SYSTEMML-1962] support model selection via mllearn api

### PR DESCRIPTION
**Pull request by j143**
Add classes for `GridSearchClassifierCV` and `GridSearchClassifierCVModel`

### CODE REVIEW

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2192/

**Comment by j143** [comment]
Hi, I use IntelliJ, I tried to change indentation but (space / tabs seletion option) is disabled. Please, share the project java best practices.

I normally code in c++, my java & python knowledge is limited & is trying improve. Please check the imports that I have done and the correctness of the classes.

**Comment by niketanpansare** [comment]
Please see http://apache.github.io/systemml/developer-tools-systemml and https://github.com/apache/systemml/tree/master/dev/code-style.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2195/

**Pull request closed without merging**
