### PR TITLE
[SYSTEMML-1325] Cleanup static variables in DMLScript

### PR DESCRIPTION
**Pull request by niketanpansare**
We use ThreadLocal DMLOptions and DMLConfig instead of static variables in DMLScript class. It allows different JMLC instances (or MLCContext instances) to run with different options (such as with GPU, with CPU, etc).

@nakul02 @thomas9t @mboehm7 Please let me know if you have suggestions or concerns regarding this PR?

### CODE REVIEW

**Comment by thomas9t** [comment]
@niketanpansare - it appears that statistics are no longer printed as expected when run via the command line:

Expected behavior is a printout of detailed SystemML statistics. However, only total execution time and number of spark instructions are printed. 
`spark-submit --jars systemml-1.3.0-SNAPSHOT-extra.jar SystemML.jar -f test-script.dml -explain -stats`

**Comment by thomas9t** [comment]
A couple issues with MLContext:

spark-shell --jars SystemML.jar,systemml-1.3.0-SNAPSHOT-extra.jar

import org.apache.sysml.api.mlcontext._
import org.apache.sysml.api.mlcontext.ScriptFactory._

```
val ml = new MLContext(spark)
val script = """
    X = rand(rows=10, cols=10)
    print("TOTAL: " + sum(X))
"""
val dmlScript = dml(script)

ml.setStatistics(true)
ml.execute(dmlScript)

org.apache.sysml.api.mlcontext.MLContextException: Exception when executing script
  at org.apache.sysml.api.mlcontext.MLContext.execute(MLContext.java:346)
  at org.apache.sysml.api.mlcontext.MLContext.execute(MLContext.java:319)
  ... 52 elided
Caused by: java.lang.RuntimeException: Multiple statistics configuration is not supported
  at org.apache.sysml.conf.ConfigurationManager.setStatistics(ConfigurationManager.java:288)
  at org.apache.sysml.conf.DMLOptions.<init>(DMLOptions.java:78)
  at org.apache.sysml.api.mlcontext.ScriptExecutor.execute(ScriptExecutor.java:339)
  at org.apache.sysml.api.mlcontext.MLContext.execute(MLContext.java:342)
  ... 53 more
```

And 

```
spark-shell --jars SystemML.jar,systemml-1.3.0-SNAPSHOT-extra.jar

import org.apache.sysml.api.mlcontext._
import org.apache.sysml.api.mlcontext.ScriptFactory._

val ml = new MLContext(spark)
val script = """
    X = rand(rows=10, cols=10)
    print("TOTAL: " + sum(X))
"""
val dmlScript = dml(script)

ml.setExplain(true)
ml.execute(dmlScript)

org.apache.sysml.api.mlcontext.MLContextException: Exception when executing script
  at org.apache.sysml.api.mlcontext.MLContext.execute(MLContext.java:346)
  at org.apache.sysml.api.mlcontext.MLContext.execute(MLContext.java:319)
  ... 52 elided
Caused by: java.lang.NullPointerException
  at org.apache.sysml.api.mlcontext.ScriptExecutor.execute(ScriptExecutor.java:337)
  at org.apache.sysml.api.mlcontext.MLContext.execute(MLContext.java:342)
  ... 53 more
```

**Comment by niketanpansare** [comment]
Thanks @thomas9t for catching that. Delivered the fix for that.

**Comment by thomas9t** [comment]
Thanks @niketanpansare - I confirm that statistics are now printed as expected when run via the command line and in MLContext.

**Comment by thomas9t** [comment]
I ran a few sanity checks on GPU behavior for MLContext and DMLScript:

1. `extra.jar` is included and GPU is not enabled -> no exception and GPU is not used
2. `extra.jar` is included and GPU is enabled -> no exception and GPU may be used
3. `extra.jar` is included and GPU is forced -> no exception and GPU is used
4. `extra.jar` is not included and GPU is not enabled -> no exception and GPU is not used
5. `extra.jar` is not included and GPU is enabled -> exception
6. `extra.jar` is not included and GPU is forced -> exception

Both APIs behave as expected. We can perform the same checks for JMLC as part of #830

**Comment by thomas9t** [comment]
@niketanpansare - I confirm that 69b991 fixed the NPE in MLContext. I also ran the standard test suite and didn't encounter any errors. I see no other issues. LGTM 👍

**Comment by niketanpansare** [comment]
Thanks @thomas9t. Will merge 👍

**Pull request closed without merging**
