### PR TITLE
[SYSTEML-1758] added cbind and rbind for GPU

### PR DESCRIPTION
**Pull request by nakul02**
Ping @niketanpansare

### CODE REVIEW

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1738/

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1739/

**Comment by niketanpansare** [comment]
LGTM ... thanks @nakul02

**Comment by nakul02** [comment]
Running the [tests](https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/294/) again.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1751/

**Comment by nakul02** [comment]
Tests passed. I shall merge.

**Pull request closed without merging**
