### PR TITLE
[SYSTEMML-1735] relational operators for GPU

### PR DESCRIPTION
**Pull request by nakul02**

### CODE REVIEW

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1668/

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1699/

**Comment by nakul02** [comment]
Ping @niketanpansare - can you please review.
All GPU tests passed.

**Comment by niketanpansare** [comment]
LGTM. Thanks @nakul02 :+1:

**Comment by nakul02** [comment]
Thanks @niketanpansare, I'll merge.

**Pull request closed without merging**
