### PR TITLE
[WIP] Implementation of SVD

### PR DESCRIPTION
**Pull request by nakul02**
@niketanpansare, @mboehm7, @bertholdreinwald, @iyounus
This initial implementation is keeping in line with the discussion on the dev mailing list.
The CP 'svd' function is implemented and backed by Apache Commons Math.

### CODE REVIEW

**Comment by niketanpansare** [comment]
As per the discussion on the mailing list, the implementations looks good to me. We should definitely consider adding lu, qr, svd, eigen to our Spark backend.

**Comment by deroneriksson** [comment]
@nakul02 @niketanpansare Can I merge this?

**Comment by niketanpansare** [comment]
I am OK with merging it in if @iyounus still wants to use it for his distributed SVD script. 
@nakul02 Please add Spark SVD instruction when you have time :)

**Comment by deroneriksson** [comment]
Thanks @niketanpansare. I'll check with @iyounus.

@iyounus @nakul02 Should this be merged?

**Comment by mboehm7** [comment]
@nakul02 could you please also add some basic tests for the svd builtin function (e.g., to org.apache.sysml.test.integration.functions.unary.matrix) and remove the wildcard import from LibCommonsMath (in order to prevent name clashes on auto import resolution)? Thanks.

**Comment by iyounus** [comment]
I don't think we should merge this right now. We still need to figure out if this is the route we're taking. What we have here may not be the right choice for SVD.

**Comment by deroneriksson** [comment]
@iyounus Thanks.

**Comment by deroneriksson** [comment]
6(!) month check-in. What's the status of this PR? Merge or close?

**Comment by iyounus** [comment]
I think we can just close this. I implemented this based on a recent paper but now I think this method is not very beneficial when it comes to scaling and that paper was somewhat misleading. So at this moment we can close this. This require some more thinking.

**Comment by deroneriksson** [comment]
@nakul02
Based on the comment from @iyounus, can we go ahead and close this PR?

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1602/

**Comment by nakul02** [comment]
Yes, I shall close it.

**Comment by j143** [comment]
@nakul02 can you rebase this branch of yours. I will clone that. Thanks.:)

**Comment by nakul02** [comment]
I've rebased it - https://github.com/nakul02/systemml/tree/svd
Here on out, you can rebase it yourself. Clone my svd branch on to the clone/fork of the systemml repository and rebase that with master.
If you run into issues doing that, please let me know.

**Pull request closed without merging**
