### PR TITLE
[SYSTEMML-1829] Add setConfig, resetConfig to Python MLContext

### PR DESCRIPTION
**Pull request by gweidner**
Added methods setConfig and resetConfig to Python MLContext for consistency.  Also included isGPU, isForceGPU wrappers to match Java MLContext.

### CODE REVIEW

**Comment by gweidner** [comment]
Tested set/resetConfig by using custom config file which enabled fine grained statistics.  Set statistics true, then ran small dml resulting in fine grain output.  Then resetConfig, reran dml, and verified normal statistics shown.

**Comment by deroneriksson** [comment]
LGTM. Thank you @gweidner!

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1889/

**Comment by gweidner** [comment]
Thank you Deron for reviewing!  I will merge.

**Pull request closed without merging**
