### PR TITLE
[WIP] Enable fine-grained statistics

### PR DESCRIPTION
**Pull request by niketanpansare**
This PR is a proposal for providing fine-grained statistics using the existing Statistics infrastructure and minimizing any additional overhead. If we don't agree on this approach, I am OK with closing the PR without merging :)

Though SystemML provides explain and statistics tooling functionality to understand the execution plan and the performance, most users (even committers) are not able to explain why SystemML's performance is so good or bad. This is likely because SystemML's optimizer performs sophisticated dataflow analysis, cost optimization as well as static and dynamic rewrites. New features/backends such as code generation, automatic fusion, compression and GPU backend adds additional level of complexity to the optimizer. This PR is a small step in the direction of explaining SystemML's behavior. 

Instead of examining statistics output (like the one given below) and then trying to correlate with the explain plan, this PR provides instruction-level statistics with the corresponding DML snippet (file beginLine:beginCol-endLine-endCol).

Current output:
```bash
Heavy hitter instructions:
  #  Instruction               Time(s)   Count
  1  forward                   134.884     516
  2  leftIndex                 102.870   66650
  3  write                      77.799     172
  4  gpu_conv2d_backward_data   26.467   66564
  5  gpu_conv2d_bias_add        17.225    2322
  6  rangeReIndex               12.987  133214
  7  rand                       10.785     517
  8  gpu_bias_add               10.615     516
  9  rmvar                       4.405  953146
 10  rshape                      3.849   38528
 11  gpu_sel+                    2.871    2752
 12  gpu_append                  1.206     516
 13  gpu_ba+*                    1.192     172
 14  gpu_r'                      0.563     344
 15  gpu_uarmax                  0.544      86
 16  gpu_uark+                   0.461      86
 17  gpu_uak+                    0.363       1
 18  createvar                   0.339  314140
 19  *                           0.189  666846
 20  gpu_/                       0.152      86
 21  gpu_-                       0.150      86
 22  gpu_maxpooling              0.087     516
 23  -                           0.049   68371
 24  +                           0.046  134848
 25  gpu_exp                     0.043      86
 26  gpu_+                       0.043     172
 27  cpvar                       0.041   68782
 28  gpu_*                       0.034     172
 29  ncol                        0.025   38012
 30  ctable                      0.024     172
```

New output with `systemml.stats.finegrained` set to `true`:
```bash
Heavy hitter instructions:
  #  Instruction                                                                        Time(s)   Count
  1  forward [261:78-261:82]                                                             59.928      86
  2  leftIndex [270:4-270:17]                                                            37.469      86
  3  write [78:2-78:2]                                                                   31.771      86
  4  leftIndex [106:4-106:42]                                                            29.836   28552
  5  forward [254:78-254:82]                                                             19.657      86
  6  forward [233:78-233:82]                                                             18.072      86
  7  gpu_conv2d_bias_add [78:2-78:2]                                                     17.235    2322
  8  gpu_conv2d_backward_data [102:4-102:4]                                              16.682   28552
  9  forward [247:78-247:82]                                                             15.004      86
 10  leftIndex [./nn/layers/conv2d_transpose_depthwise.dml 106:4-106:42]                 11.250   38012
 11  gpu_conv2d_backward_data [./nn/layers/conv2d_transpose_depthwise.dml 102:4-102:4]   10.417   38012
 12  rangeReIndex [101:4-101:5]                                                           9.289   28552
 13  forward [225:78-225:82]                                                              8.800      86
 14  forward [240:78-240:82]                                                              8.069      86
 15  rand [88:2-88:2]                                                                     7.665     258
 16  write [227:26-227:30]                                                                5.422      86
 17  gpu_bias_add [110:2-110:2]                                                           5.369     258
 18  rmvar [-1:-1--1:-1]                                                                  4.634  953140
 19  rand [./nn/layers/conv2d_transpose_depthwise.dml 88:2-88:2]                          2.879     258
 20  rangeReIndex [./nn/layers/conv2d_transpose_depthwise.dml 101:4-101:5]                2.756   38012
 21  gpu_sel+ [78:2-78:2]                                                                 2.111    2236
 22  gpu_bias_add [./nn/layers/conv2d_transpose_depthwise.dml 110:2-110:2]                1.873     258
 23  rshape [289:26-289:26]                                                               1.802     172
 24  rshape [289:2-289:2]                                                                 1.767     172
 25  rangeReIndex [188:95-188:96]                                                         1.013      86
 26  gpu_ba+* [289:26-289:2]                                                              0.837     172
 27  gpu_append [263:4-263:4]                                                             0.713      86
 28  gpu_uak+ [unet.dml 272:6-272:6]                                                      0.703       1
 29  gpu_uarmax [52:20-52:20]                                                             0.536      86
 30  gpu_uark+ [54:25-54:25]                                                              0.464      86
```

How does this help ?  The script we ran had three left indexing operations: two in the file `conv2d_transpose_depthwise.dml` and one in the main script at line 270. However the information `  2  leftIndex                 102.870   66650` is not sufficient to help the DML script writer understand where exactly is the bottleneck. Separating the different instances of `leftIndex` instructions provides much better picture:

```bash
  2  leftIndex [270:4-270:17]                                                            37.469      86
  4  leftIndex [106:4-106:42]                                                            29.836   28552
 10  leftIndex [./nn/layers/conv2d_transpose_depthwise.dml 106:4-106:42]                 11.250   38012
```

As you may have noticed, there are additional TODO items which may have to be addressed in a separate PR. For example: certain line numbers correspond to the parent expression `4  leftIndex [106:4-106:42]`  corresponds to the variable initialized in line 106 of the main script, but the leftIndex operation was actually performed in the file `conv2d_transpose_depthwise.dml`.

@bertholdreinwald @mboehm7 @dusenberrymw @nakul02 @deroneriksson Please review this PR and provide your suggestions and concerns.

### CODE REVIEW

**Comment by mboehm7** [comment]
Do you really think that's a good idea? Our stats output is meant to provide concise summary statistics, while these statistics here with their extended opcodes seem to be too convoluted for most users. At the same time, they simply do not provide sufficient information for dev performance debugging (e.g., breakdowns of sparse/dense, input/output data sizes, performance per category), which renders them - at least for me - useless. So to avoid yet another configuration property, I would recommend to drop this.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1764/

**Comment by nakul02** [comment]
@niketanpansare - I am all for finer grained statistics. These are useful, specially for someone like trying to debug performance problems in a large complicated DML Script. 

In fact, if you've seen the GPU extra statistics, I would love to have that for all the important ops. 

As of now, what we get are aggregated numbers and it is very hard to glean **where** something is going wrong.  (for instance, if a `ba+*` takes 90% of the time, I cannot tell which particular instance of the call is actually taking the most amount of time).

Also, since this is being introduced as a configuration property, IMO, it is ok to add. 

This is just me. I would ask @dusenberrymw to weigh in, since he has a lot of experience developing and running DML programs.

**Comment by deroneriksson** [comment]
Being able to optionally turn on fine-grained statistics seems like it has the potential to be useful to begin to narrow down the causes of performance issues.

**Comment by mboehm7** [comment]
Maybe we all understand something different under "performance profiling" but from my perspective it is not useful to extend the opcode by the line numbers. Assume you have a function foo that is called with different sizes and sparse/dense matrices. The extended opcode, let's say for a particular indexing operation, in foo still mixes up completely different characteristics. What we usually do is to determine the major bottleneck via stats and subsequently instrument the code to get the actual relevant breakdown for dense/sparse, different code paths, and so on.

**Comment by niketanpansare** [comment]
For initial profiling or for high-level understanding, I agree with @nakul02 , @deroneriksson and @dusenberrymw on the utility of providing the line numbers especially since this is an optional feature with no overhead.  

For advanced profiling, based on @mboehm7 and @nakul02 feedback, may be we can further extend this to provide additional breakdown without requiring instrumentation of the code, as the instrumented code cannot be reused by others ... let's discuss this approach in a separate PR. For example with `systemml.stats.extraCP` flag:

```bash
Heavy hitter instructions:
  #  Instruction                                                                        Time(s)   Count  GPU/CP
  1  forward [261:78-261:82]                                                             60.436      86
  2  leftIndex [270:4-270:17]                                                            37.353      86  sp[x, 80], dn[37.353-x, 6]
  3  leftIndex [106:4-106:42]                                                            30.004   28552
  4  forward [254:78-254:82]                                                             19.012      86
  5  forward [233:78-233:82]                                                             18.822      86
  6  gpu_conv2d_backward_data [102:4-102:4]                                              17.411   28552  nnc[0.023s,28552], ad[0.447s,28552], H2D[13.645s,57104], s2d[1.261s,16765], nncbd[1.335s,28552], nni[1.568s,28552]
  7  gpu_conv2d_bias_add [78:2-78:2]                                                     17.069    2322  nnrbk[16.405s,2322], nnc[0.003s,2322], nni[0.016s,2322], ad[0.066s,2322], nncf[0.111s,2322], H2D[0.232s,140]
  8  forward [247:78-247:82]                                                             15.680      86
  9  leftIndex [./nn/layers/conv2d_transpose_depthwise.dml 106:4-106:42]                 12.054   38012
 10  gpu_conv2d_backward_data [./nn/layers/conv2d_transpose_depthwise.dml 102:4-102:4]    9.792   38012  nnc[0.024s,38012], s2d[0.380s,5874], ad[0.489s,38012], nni[0.656s,38012], nncbd[1.576s,38012], H2D[6.625s,76024]
 11  forward [225:78-225:82]                                                              9.575      86
 12  rangeReIndex [101:4-101:5]                                                           9.077   28552
 13  rand [88:2-88:2]                                                                     8.046     258
 14  forward [240:78-240:82]                                                              7.911      86
 15  gpu_bias_add [110:2-110:2]                                                           5.651     258  ad[0.012s,258], nnrbk[0.475s,258], H2D[5.151s,261]
```

**Comment by niketanpansare** [comment]
An example statistics for CP that might address @mboehm7 's concerns as well as make the instrumentation reusable :)

```
  2  leftIndex [268:4-268:17]                 43.341      86  aqrd[0.000s,172], rls[0.000s,172], lixcp[0.516s,86]
  3  leftIndex [108:4-108:42]                 31.743   66564  aqrd[23.509s,133128], lixcp[7.464s,66564], rls[0.073s,133128]
```

**Comment by deroneriksson** [comment]
I tried out the `systemml.stats.finegrained`, and IMO, this looks very useful, especially for contributors such as myself who have limited profiling experience with the project. I believe I will use this a lot. Thank you @niketanpansare. LGTM.

@niketanpansare @nakul02 Would it be possible to allow this to be turned on via MLContext and DMLScript?

**Comment by niketanpansare** [comment]
Ideally yes via `setConfigProperty`, but I can double-check :)

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1783/

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1786/

**Comment by niketanpansare** [comment]
@deroneriksson  With recent bugfix in this PR, this feature can be turned on via MLContext as well:

```python
import numpy as np
from sklearn import datasets
from systemml.mllearn import LinearRegression
# Load the diabetes dataset
diabetes = datasets.load_diabetes()
# Use only one feature
diabetes_X = diabetes.data[:, np.newaxis, 2]
# Split the data into training/testing sets
X_train = diabetes_X[:-20]
X_test = diabetes_X[-20:]
# Split the targets into training/testing sets
y_train = diabetes.target[:-20]
y_test = diabetes.target[-20:]
# Create linear regression object
regr = LinearRegression(spark, fit_intercept=True, C=float("inf"), solver='direct-solve').setStatistics(True).setConfigProperty("systemml.stats.finegrained", "true")
# Train the model using the training sets
regr.fit(X_train, y_train)
```

This outputs:
```bash
SystemML Statistics:
Total elapsed time:             0.060 sec.
Total compilation time:         0.000 sec.
Total execution time:           0.060 sec.
Number of compiled Spark inst:  2.
Number of executed Spark inst:  2.
Cache hits (Mem, WB, FS, HDFS): 26/0/0/0.
Cache writes (WB, FS, HDFS):    1/0/0.
Cache times (ACQr/m, RLS, EXP): 0.000/0.000/0.001/0.000 sec.
HOP DAGs recompiled (PRED, SB): 0/0.
HOP DAGs recompile time:        0.000 sec.
Spark ctx create time (lazy):   0.000 sec.
Spark trans counts (par,bc,col):0/0/0.
Spark trans times (par,bc,col): 0.000/0.000/0.000 secs.
Total JIT compile time:         11.626 sec.
Total JVM GC count:             6.
Total JVM GC time:              0.219 sec.
Heavy hitter instructions:
  #  Instruction               Time(s)  Count  Misc Timers
  1  solve [148:0-148:0]         0.027      1  aqmd[0.000s,1]
  2  tsmm [137:4-137:13]         0.008      1  rlsi[0.000s,1], aqmd[0.000s,1], aqrd[0.000s,1]
  3  uak+ [161:10-161:10]        0.007      1  aqrd[0.000s,1], rlsi[0.000s,1]
  4  ba+* [138:4-138:13]         0.005      1  aqmd[0.000s,1], aqrd[0.000s,2], rlsi[0.000s,2]
  5  rand [89:0-89:0]            0.004      1  aqmd[0.000s,1]
  6  * [133:9-133:24]            0.002      1  aqmd[0.000s,1], aqrd[0.000s,1], rlsi[0.000s,1]
  7  r' [138:4-138:13]           0.001      2  aqmd[0.000s,2], aqrd[0.000s,2], rlsi[0.000s,2]
  8  append [97:4-97:4]          0.001      1  rlswr[0.000s,1], aqmd[0.000s,1], rlsev[0.000s,0], aqrd[0.000s,2], rlsi[0.000s,2]
  9  + [144:4-144:21]            0.001      1  aqmd[0.000s,1], aqrd[0.000s,2], rlsi[0.000s,2]
 10  leftIndex [104:4-104:26]    0.001      1  aqmd[0.000s,1], rlsi[0.000s,1], aqrd[0.000s,1]
```

For the given cluster and data characteristics, the three heavy hitters are broken down along with their input MB types (all are dense in this case). For custom code path, please see the [comment](https://github.com/niketanpansare/systemml/blob/b7ed58b4338f6448a3dd39c3778fc96a09e3c861/src/main/java/org/apache/sysml/runtime/instructions/cp/CPInstruction.java#L56). 

Thanks @deroneriksson for LGTM. I will hold off on merging this PR for 24 hours to give other committers an opportunity to provide feedback. After that, I will merge :)

**Comment by deroneriksson** [comment]
Thanks @niketanpansare.

**Pull request closed without merging**
