### PR TITLE
[SYSTEMML-1606] Update notebook samples with latest code

### PR DESCRIPTION
**Pull request by asurve**
Updated code to work with latest SystemML code.
  - Updated following line with setRawPredictionCol("prediction"), as code was throwing an exception "java.lang.IllegalArgumentException: Field "rawPrediction" does not exist."

     BinaryClassificationEvaluator).setRawPredictionCol("prediction"))

@niketanpansare Please look at the changes.

### CODE REVIEW

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1469/

**Comment by deroneriksson** [comment]
cc @niketanpansare

**Comment by niketanpansare** [comment]
There is a bug in scala logistic regression that needs to be fixed. Setting prediction to raw prediction might not fix the issue. Here is my recommendation to be consistent wrt this notebook:
1. Create a separate PR and delete this notebook.
2. Keep this PR open until the bug is fixed.
3. Once the bug is fixed, merge the notebook :)

**Comment by dusenberrymw** [comment]
Can this be updated now?

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1767/

**Comment by j143** [comment]
Let us close this one for now.

**Pull request closed without merging**
