### PR TITLE
[SYSTEMML-1698] Deep Learning in menu of DML Lang Ref

### PR DESCRIPTION
**Pull request by feihugis**

### CODE REVIEW

**Comment by akchinSTC** [comment]
Can an Admin verify this patch?

**Comment by deroneriksson** [comment]
Test this Jenkins

**Comment by deroneriksson** [comment]
add to whitelist.

**Comment by deroneriksson** [comment]
LGTM. Thank you @feihugis!

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1587/

**Pull request closed without merging**
