### PR TITLE
Implementation of Neural Collaborative Filtering (NCF)

### PR DESCRIPTION
**Pull request by deutschmn**
This pull request adds an implementation of Neural Collaborative Filtering (NCF) using the SystemDS NN library. 

The concept is based on [this paper ](https://dl.acm.org/doi/abs/10.1145/3038912.3052569) and implements a fixed architecture – details are described in the `README.md` of the examples for the NN library. 

The implementation includes: 
- `NCF.dml`: train, predict and evaluate an NCF model
- `ncf-dummy-data.dml` train the model with synthetic data (fast)
- `ncf-real-data.dml` train the model with the MovieLens data set (takes some time)
- `Example - Neural Collaborative Filtering.ipynb`: a Jupyter notebook to download the data, prepare it, call the training scripts and plot the training history

Some remarks:
- This implementation has a fixed network architecture for three dense layers. I was thinking about making it dynamic, but this would require all weights and biases to be stored in untyped lists, which I feared would kill performance. 
- For now the implementation does not add any tests, as it's rather a demonstration of how SystemDS can be used and not a part that can easily be reused for a different use case. Also, I wasn't sure what to test against, since the network doesn't have any clear expected output.
- I now implemented it as a script file rather than as a built-in functions, as built-ins would cross-reference each other and also make use of the NN-library, which itself isn't a built-in. If these issues are resolved, it could, however, be ported over to a built-in.

EDIT (by @j143): (A different PR can also be opened for the following, if you like!)
- [ ] Regarding testing, we do some [gradient checking](https://github.com/apache/systemml/blob/405462e84ad1192e447bb09c03fe20d112bf6afb/scripts/nn/test/grad_check.dml#L1133) like `fm`.
- [ ] If you are planning add to NCF documentation. A pointer would be [FM doc](https://github.com/apache/systemml/pull/729/files)
or you can simply add a TODO. :)

### CODE REVIEW

**Comment by j143** [comment]
Hi @deutschmn - Since this PR is here for a while I will make a preliminary pass. :)

**Comment by j143** [comment]
Hi @deutschmn,

Dev notebook for this PR: https://gist.github.com/j143/df1fdea505df2c662b326bd689bf5a0d
One could run it on colab with symbol
image available at the link.

Running with real-data is taking forever. Could you have a look at the above notebook? :)

**Comment by j143** [comment]
Output on my end: 🔢 
Graph output:
image

log (first few lines):
`bin/systemds target/SystemDS.jar -f scripts/nn/examples/ncf-real-data.dml`
```console
Executing command:     java       -Xmx4g      -Xms4g      -Xmn400m   -cp target/SystemDS.jar:./lib/*:./target/lib/*   -Dlog4j.configuration=file:conf/log4j-silent.properties   org.apache.sysds.api.DMLScript   -f scripts/nn/examples/ncf-real-data.dml   -exec singlenode      

Done reading.
Done encoding.
NCF training starting with 80670 training samples, 20168 validation samples, 193609 items and 610 users...
Epoch: 1, Iter: 1, Train Loss: 0.707747965832602, Train Accuracy: 0.125, Val Loss: 0.7174051262289975, Val Accuracy: 0.16322887742959147
Epoch: 1, Iter: 101, Train Loss: 0.0019915228635854288, Train Accuracy: 1.0, Val Loss: 0.00204491822016021, Val Accuracy: 1.0
Epoch: 1, Iter: 201, Train Loss: 4.2908920275443456E-4, Train Accuracy: 1.0, Val Loss: 4.3745282125570923E-4, Val Accuracy: 1.0
Epoch: 1, Iter: 301, Train Loss: 1.9717089553763218E-4, Train Accuracy: 1.0, Val Loss: 1.9359771305085208E-4, Val Accuracy: 1.0
Epoch: 1, Iter: 401, Train Loss: 1.0429772240279489E-4, Train Accuracy: 1.0, Val Loss: 1.0826596717454964E-4, Val Accuracy: 1.0
Epoch: 1, Iter: 501, Train Loss: 5.9287790346766694E-5, Train Accuracy: 1.0, Val Loss: 6.882931463477808E-5, Val Accuracy: 1.0
Epoch: 1, Iter: 601, Train Loss: 5.664888697342753E-5, Train Accuracy: 1.0, Val Loss: 4.7765565448656784E-5, Val Accuracy: 1.0
Epoch: 1, Iter: 701, Train Loss: 3.255122311021885E-5, Train Accuracy: 1.0, Val Loss: 3.477534652921848E-5, Val Accuracy: 1.0
Epoch: 1, Iter: 801, Train Loss: 3.084381497330652E-5, Train Accuracy: 1.0, Val Loss: 2.6579394310844034E-5, Val Accuracy: 1.0
Epoch: 1, Iter: 901, Train Loss: 2.3561183906885313E-5, Train Accuracy: 1.0, Val Loss: 2.1187621742893348E-5, Val Accuracy: 1.0
Epoch: 1, Iter: 1001, Train Loss: 1.3961509447494607E-5, Train Accuracy: 1.0, Val Loss: 1.7119065813537224E-5, Val Accuracy: 1.0
Epoch: 1, Iter: 1101, Train Loss: 1.2252708016537367E-5, Train Accuracy: 1.0, Val Loss: 1.4191927338834147E-5, Val Accuracy: 1.0
```

**Comment by deutschmn** [comment]
Hi @j143,

thanks for having a look at my PR! 

Sorry, I realised I still had a very low number for the negative samples in the Jupyter notebook. That caused the network to learn that basically almost every label should be 1 and hence immediately reached nearly zero loss. 

I corrected the issue in the most recent commit and in the Colab notebook 😊 Not sure, if that's the same for everyone though.

Cheers,
Patrick

**Comment by j143** [comment]
with negative_split = 1.5 :)

output graph: (Could not run the whole of the training though, Colab have a disk 80GB)
image

**Comment by j143** [comment]
This initial implementation looks good to me. 👍 
I am not planning to merge this though. :)

**Comment by deutschmn** [comment]
Thanks for the feedback, @j143! How do I move on from here, @mboehm7? 😊

**Comment by mboehm7** [comment]
LGTM - thanks @deutschmn for the new algorithm and examples, and @j143 for trying it out. Overall this is really great and I agree that it's best placed under staging right now. We'll follow up once the prerequisites are properly setup. During the merge I only fixed minor typos and formatting issues.

**Pull request closed without merging**
