### PR TITLE
[SYSTEMML-1738] [minor] close the input stream

### PR DESCRIPTION
**Pull request by j143**
1. The input stream is to be closed as pointed out by Ted Yu.
2. But, may not be required considering, file name is a small string.
3. Please, feel free to close this PR. If the change is not needed.

### CODE REVIEW

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2318/

**Comment by j143** [comment]
ping @mboehm7 . Thanks.

**Comment by mboehm7** [comment]
Usually, the stream should be closed where it is created. This means if the input stream is passed from outside, we should leave it along even if it's read entirely. However, for all cases where we create stream, we should indeed close it. Please use `IOUtilFunctions.closeSilently()` to avoid unnecessary exception handling, or even better use try-with-resource where the stream is created - that way its automatically closes with proper finally semantics.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2319/

**Comment by mboehm7** [comment]
Just to clarify my dev list entry - this change can still go into SystemML 1.1 if the needed modifications are ready in the next days.

**Comment by j143** [comment]
I've used `IOUtilFunctions.closeSilently()`, for closing, instead of try with resource. Thanks.

**Comment by mboehm7** [comment]
No it's still in the wrong place. Please have a look at the call hierarchy of `scriptFromInputStream`. Then you will see that it's used three times, of which two already use the try-with-resource. The only open issue it in `scriptFromResource` which should similarly wrap the input stream creation into try, which will automatically close the input stream.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2322/<h2>Failed Tests: <span class='status-failure'>4</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2322/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>4</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2322/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/ParUnaryAggregateTest/testSumDenseConstantDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.ParUnaryAggregateTest.testSumDenseConstantDataCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2322/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/ParUnaryAggregateTest/testSumDenseRoundRandDataDDCCompression/'><strong>org.apache.sysml.test.integration.functions.compress.ParUnaryAggregateTest.testSumDenseRoundRandDataDDCCompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2322/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/ParUnaryAggregateTest/testSumDenseRoundRandDataOLECompression/'><strong>org.apache.sysml.test.integration.functions.compress.ParUnaryAggregateTest.testSumDenseRoundRandDataOLECompression</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2322/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.compress/ParUnaryAggregateTest/testSumDenseRandDataCompression/'><strong>org.apache.sysml.test.integration.functions.compress.ParUnaryAggregateTest.testSumDenseRandDataCompression</strong></a></li></ul>

**Comment by mboehm7** [comment]
thanks @j143 - I fixed and merged it now but please have a look maybe it clarifies my previous statement.

**Pull request closed without merging**
