### PR TITLE
[WIP][SYSTEMML-976] Add explain and stats option to Python DSL

### PR DESCRIPTION
**Pull request by j143-zz**
- [x] Extend `def eval(outputs, outputDF=False, execute=True):` method to accept explain and statistics options and pass them before `results = matrix.ml.execute(matrix.script)`.

- [ ] Expose these options through user facing APIs: `eval()` and methods that invoke eval (such as `toPandas`, `toNumPyArray`, `toDataFrame`, etc)

### CODE REVIEW

**Comment by j143** [comment]
ping @krishnakalyan3 .

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2314/<h2>Failed Tests: <span class='status-failure'>2</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2314/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>2</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2314/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.codegenalg/AlgorithmPNMF/testPNMFDenseCPFuseNoRedundancy/'><strong>org.apache.sysml.test.integration.functions.codegenalg.AlgorithmPNMF.testPNMFDenseCPFuseNoRedundancy</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2314/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.codegenalg/AlgorithmPNMF/testPNMFSparseCPFuseNoRedundancy/'><strong>org.apache.sysml.test.integration.functions.codegenalg.AlgorithmPNMF.testPNMFSparseCPFuseNoRedundancy</strong></a></li></ul>

**Comment by krishnakalyan3** [comment]
Test this Jenkins

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2315/<h2>Failed Tests: <span class='status-failure'>2</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2315/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>2</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2315/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.codegenalg/AlgorithmPNMF/testPNMFDenseCPFuseNoRedundancy/'><strong>org.apache.sysml.test.integration.functions.codegenalg.AlgorithmPNMF.testPNMFDenseCPFuseNoRedundancy</strong></a></li><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2315/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.functions.codegenalg/AlgorithmPNMF/testPNMFSparseCPFuseNoRedundancy/'><strong>org.apache.sysml.test.integration.functions.codegenalg.AlgorithmPNMF.testPNMFSparseCPFuseNoRedundancy</strong></a></li></ul>

**Pull request closed without merging**
