### PR TITLE
Added tiny LSTM example to illustrate usage

### PR DESCRIPTION
**Pull request by romeokienzler**
Thanks to Prithviraj Sen for contributing his code

### CODE REVIEW

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1980/

**Comment by deroneriksson** [comment]
ping @bertholdreinwald @prithvirajsen

**Comment by romeokienzler** [comment]
ping @bertholdreinwald @prithvirajsen :)

**Comment by romeokienzler** [comment]
@niketanpansare I prefer if we can got with that for now. I'll work on some keras-lstm->SystemML examples, so they IMHO will use the newer LSTM kernel anyway

**Comment by niketanpansare** [comment]
@romeokienzler I will add newer kernel in Keras2DML this week :)

@j143-bot Let me know if you prefer to use the simpler lstm kernel.

**Pull request closed without merging**
