### PR TITLE
[SYSTEMML-1731]  Missing element wise instructions for GPU

### PR DESCRIPTION
**Pull request by nakul02**

### CODE REVIEW

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1632/

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1649/

**Comment by nakul02** [comment]
@niketanpansare - can you please review this?
GPU Instructions added - 1-*, -nz, %%, %/%

**Comment by niketanpansare** [comment]
LGTM. Thanks @nakul02 👍

**Comment by nakul02** [comment]
Thanks @niketanpansare, I shall merge.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1660/

**Pull request closed without merging**
