### PR TITLE
[MINOR] Enable systemml to be imported in the pyspark workers

### PR DESCRIPTION
**Pull request by niketanpansare**
- Moved the race condition avoidance logic to toDF method instead of import level. This avoids creation of dataframe in pyspark workers.

@asurve @bertholdreinwald can you please review this PR  ?

### CODE REVIEW

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2040/

**Comment by asurve** [comment]
I looked at the code, not sure if adding this functionality may cause issue anywhere else.
I run the scenario with latest code and changes from this PR, I had issue earlier and its working fine.

LGTM

**Comment by niketanpansare** [comment]
thanks @asurve ... I will merge :+1:

**Comment by niketanpansare** [comment]
Thanks @asurve I made few more changes to ensure that KDD tutorial is working too. Can you please double-check if the new changes fixes your issue ?

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/2052/

**Comment by asurve** [comment]
This code may be better than earlier one, as not dependent on always/through toDF(). Its loaded in class loader.

I have tried my scenario and works fine.

**Pull request closed without merging**
