### PR TITLE
[SYSTEMML-1774] Bugfix for NPE in relu backward instruction

### PR DESCRIPTION
**Pull request by niketanpansare**
@dusenberrymw @feihugis can you please review this PR ?

### CODE REVIEW

**Comment by feihugis** [comment]
@niketanpansare Thanks for your help! I test it on my local machine. There are still some errors as following, but they are different with the previous ones.

~~~java
17/07/18 14:29:33 INFO DAGScheduler: ResultStage 2 (collect at RemoteParForSpark.java:77) failed in 2.122 s due to Job aborted due to stage failure: Task 1 in stage 2.0 failed 1 times, most recent failure: Lost task 1.0 in stage 2.0 (TID 5, localhost, executor driver): org.apache.sysml.runtime.DMLRuntimeException: ERROR: Runtime error in program block generated from statement block between lines 0 and 0 -- Error evaluating instruction: CP°relu_backward°outa3·MATRIX·DOUBLE°_mVar3921·MATRIX·DOUBLE°_mVar3923·MATRIX·DOUBLE°-1
	at org.apache.sysml.runtime.controlprogram.ProgramBlock.executeSingleInstruction(ProgramBlock.java:316)
	at org.apache.sysml.runtime.controlprogram.ProgramBlock.executeInstructions(ProgramBlock.java:217)
	at org.apache.sysml.runtime.controlprogram.ProgramBlock.execute(ProgramBlock.java:163)
	at org.apache.sysml.runtime.controlprogram.parfor.ParWorker.executeSetTask(ParWorker.java:167)
	at org.apache.sysml.runtime.controlprogram.parfor.ParWorker.executeTask(ParWorker.java:136)
	at org.apache.sysml.runtime.controlprogram.parfor.RemoteParForSparkWorker.call(RemoteParForSparkWorker.java:75)
	at org.apache.sysml.runtime.controlprogram.parfor.RemoteParForSparkWorker.call(RemoteParForSparkWorker.java:40)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$3$1.apply(JavaRDDLike.scala:143)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$3$1.apply(JavaRDDLike.scala:143)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:935)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:935)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1944)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1944)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.sysml.runtime.DMLRuntimeException: Error while executing multi-threaded tasks
	at org.apache.sysml.runtime.matrix.data.LibMatrixDNN.execute(LibMatrixDNN.java:536)
	at org.apache.sysml.runtime.matrix.data.LibMatrixDNN.reluBackward(LibMatrixDNN.java:391)
	at org.apache.sysml.runtime.instructions.cp.ConvolutionCPInstruction.processReluBackwardInstruction(ConvolutionCPInstruction.java:231)
	at org.apache.sysml.runtime.instructions.cp.ConvolutionCPInstruction.processInstruction(ConvolutionCPInstruction.java:320)
	at org.apache.sysml.runtime.controlprogram.ProgramBlock.executeSingleInstruction(ProgramBlock.java:286)
	... 31 more
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: fromIndex(512) > toIndex(1)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.sysml.runtime.matrix.data.LibMatrixDNN.execute(LibMatrixDNN.java:532)
	... 35 more
Caused by: java.lang.IllegalArgumentException: fromIndex(512) > toIndex(1)
	at java.util.Arrays.rangeCheck(Arrays.java:113)
	at java.util.Arrays.fill(Arrays.java:3079)
	at org.apache.sysml.runtime.util.ConvolutionUtils.binaryOperationInPlace(ConvolutionUtils.java:95)
	at org.apache.sysml.runtime.matrix.data.LibMatrixDNNHelper$ReluBackward.call(LibMatrixDNNHelper.java:234)
	at org.apache.sysml.runtime.matrix.data.LibMatrixDNNHelper$ReluBackward.call(LibMatrixDNNHelper.java:208)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
~~~

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1773/

**Comment by feihugis** [comment]
@niketanpansare The error seems to be caused by [this line](https://github.com/apache/systemml/blob/master/src/main/java/org/apache/sysml/runtime/util/ConvolutionUtils.java#L95). It may be fixed by changing it to `Arrays.fill(dest, cix+prevDestIndex, cix+aix[j], 0)`. Could you help check it?

**Comment by dusenberrymw** [comment]
@feihugis Awesome, can you create a PR with your fix?

**Comment by feihugis** [comment]
@niketanpansare @dusenberrymw The [PR](https://github.com/apache/systemml/pull/584) is created to fix the error `java.lang.IllegalArgumentException: fromIndex(512) > toIndex(1)`. Could you help review it?

**Pull request closed without merging**
