### PR TITLE
[MINOR] Fix javadoc warning

### PR DESCRIPTION
**Pull request by gweidner**
Add `@throws DMLRuntimeException` to javadoc comment to remove build warning during javadoc generation.  Also included javadoc comments for other public methods for consistency following pattern used in MLContext.

### CODE REVIEW

**Comment by nakul02** [comment]
Thanks @gweidner, LGTM :+1:

**Comment by deroneriksson** [comment]
LGTM. No javadoc warning appears now during the build. Thank you for adding the additional javadocs too.

**Comment by gweidner** [comment]
Thank you @nakul02 and @deroneriksson for reviewing!  I will merge.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1941/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='SystemML-PullRequestBuilder/org.apache.systemml:systemml' /><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1941/org.apache.systemml$systemml/testReport'>SystemML-PullRequestBuilder/org.apache.systemml:systemml</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1941/org.apache.systemml$systemml/testReport/org.apache.sysml.test.integration.mlcontext/MLContextTest/testCreateDMLScriptBasedOnURL/'><strong>org.apache.sysml.test.integration.mlcontext.MLContextTest.testCreateDMLScriptBasedOnURL</strong></a></li></ul>

**Pull request closed without merging**
