### PR TITLE
[SYSTEMML-703] Prepare for GPU on Jenkins, disable expensive NN tests

### PR DESCRIPTION
**Pull request by nakul02**
@asurve - To run the GPU tests on the Jenkins machines, use this line:
```
mvn clean verify -PgpuTests
```

### CODE REVIEW

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1620/

**Comment by dusenberrymw** [comment]
Curious, aside from the `testMaxPoolBackward ` test, roughly how long do the other NN tests take?

**Comment by nakul02** [comment]
The `conv2d*` tests did not finish, because of [JIRA 1650 ](https://issues.apache.org/jira/browse/SYSTEMML-1650)

**Comment by dusenberrymw** [comment]
Ah yeah, that's right.  I was also thinking that we could force the [NNTest.java](https://github.com/apache/systemml/blob/master/src/test/java/org/apache/sysml/test/integration/scripts/nn/NNTest.java) tests to run on a GPU if available, since those won't take as long, but they will fail for that same reason.

**Comment by nakul02** [comment]
Ping @asurve - let me know when you want me to merge this.

**Comment by asurve** [comment]
LGTM

**Comment by nakul02** [comment]
thanks @asurve, I shall merge

**Pull request closed without merging**
